### ISSUE TITLE
upgrade 4.13 - 4.15 failing

### ISSUE THREAD

**Issue by klauskobald** [wave-harmonic/crest#1010]
**Describe the bug**
I am getting this error:
Shader error in 'Crest/Inputs/Dynamic Waves/Sphere-Water Interaction': Couldn't open include file '../../OceanInputsDriven.hlsl'. at line 26

In fact that path is wrong. it should be: ../OceanInputsDriven.hlsl

Question: is this deprecated stuff - so you did maybe forget about it? 
I did not change anything after updating, but in the change log I read about easier water interaction setup. What Do I need to change? I see the water interaction as I have set it up actually behaves differently.

**Comment by daleeidd** [comment]
Sorry about that. It was a mistake as we forgot to add a dummy file to prevent this from happening when we moved the file. Closing as duplicate issue of #971.

**Comment by daleeidd** [comment]
> I did not change anything after updating, but in the change log I read about easier water interaction setup. What Do I need to change? I see the water interaction as I have set it up actually behaves differently.

Sphere Water Interaction is now just a script. No meshes renderers or anything required.

**Comment by klauskobald** [comment]
That´s a big improvement. Love it. I still need some script to adapt values to different speeds, but that´s fine.
