### ISSUE TITLE
Allow dynamic resolution breaks depth texture sampling

### ISSUE THREAD

**Issue by klauskobald** [wave-harmonic/crest#1014]
**Describe the bug**
When allowDynamicResolution is used on the main camera with a value ≠1, the shadow is not scaled appropriately.

**Screenshots / video**

<img width="457" alt="image" src="https://user-images.githubusercontent.com/278428/167091821-bf2fe706-26fc-42db-82de-04cb23909e3c.png">

**Comment by klauskobald** [comment]
Wrong ! 
Shadow seems to be ok. But what´s the gray thing then?

**Comment by klauskobald** [comment]
I decided to use the scaling setting in the renderpipeline. This works.
So feel free to close the issue, if you think it's not so important for now.

**Comment by daleeidd** [comment]
Closing as I couldn't reproduce this one in Crest 4.16 and Unity 2020.3.40. Please reopen if it is still a problem.
