### ISSUE TITLE
Crest Ocean System URP Flickering Green Lines / Foam Coverage

### ISSUE THREAD

**Issue by fatboxSoftware** [wave-harmonic/crest#1040]
In a default URP project with no external plugins installed, Crest appears to have green scintillating lines covering the entire mesh/material ocean object. The foam also covers every square inch of the mesh/material object.

Here is a video capturing the issue: 
https://youtu.be/YlEN6ON_xrM

Editor log shows an error being spammed: "Shader warning in 'FFTCompute': HLSLcc: The resource '_Output' uses an unsupported type/format at kernel ComputeFFT (on gles3)" and "Shader warning in 'FFTSpectrum': HLSLcc: The resource '_ResultDisplaceX' uses an unsupported type/format at kernel SpectrumUpdate (on gles3)" and "Shader warning in 'ShapeCombine': HLSLcc: The resource '_LD_TexArray_AnimatedWaves_Compute' uses an unsupported type/format for read/write access at kernel ShapeCombine_FLOW_ON_DYNAMIC_WAVE_SIM_ON (on gles3)"

Unity Editor 2021.3.2f1. URP 12.1.6

Import CREST into URP project and look for issue.

Android/XR

Desktop machine. 3090 RTX Nvidia GPU, 32GB of RAM, Intel I9

**Comment by daleeidd** [comment]
Crest doesn't support OpenGL or WebGL. Have you tried Vulkan?

**Comment by fatboxSoftware** [comment]
> Crest doesn't support OpenGL or WebGL. Have you tried Vulkan?

I'm giving Vulkan a try this morning. Thank you for that info. I seemed to have overlooked it to be honest.

**Comment by daleeidd** [comment]
I'll probably acquire a Quest in the coming months and see if I can get Crest working. But if anyone else works out this problem feel free to let us know here.

**Comment by cloudwalker2020** [comment]
Any update on this one?

**Comment by daleeidd** [comment]
Also setting the Windows Graphics API to Vulkan appears to solve the problem (assuming you're on Windows). Thank you @cloudwalker2020 for the tip.

I have submitted a bug report to Unity as I could not see a problem with our shader.

**Comment by daleeidd** [comment]
Issue: https://issuetracker.unity3d.com/product/unity/issues/guid/UUM-20624
