### ISSUE TITLE
Problem with SphereWaterInteraction script on console

### ISSUE THREAD

**Issue by IsmarBornGames** [wave-harmonic/crest#1048]
The game crash when the scene is loaded, but this only on the build  (console and pc build)
On the PC build, the game can be played, wiothout waves and water interactions, buit in the console build the game crash

**Log**
In the log says continiously the same thing 
(this is on the console build)
![Captura](https://user-images.githubusercontent.com/106060935/172604655-ec4edd2f-3b4d-4923-9bda-f49c856250d7.PNG)
(this is on the pc build)
![Captura](https://user-images.githubusercontent.com/106060935/172604866-04de06ac-344d-42cb-8216-19617af5f61a.PNG)

**Versions**
We are now using the Crest 4.14 on the HDRP 12.1.4 and the unity version is the 2021.2.12

**To Reproduce**
The error reproduces when oppening the scene, and also happens on the example scenes.

**Platform**
PC standalone and PS5

**Comment by daleeidd** [comment]
Thank you for reporting. This is a duplicate issue of #971 which has solutions including upgrading to latest version.
