### ISSUE TITLE
Entering and exiting play mode makes ocean tiles pickable again

### ISSUE THREAD

**Issue by huwb** [wave-harmonic/crest#1056]
**Describe the bug**

If you disable picking of the ocean gameobject to stop the ocean being pickable, this propagates the setting to the tiles and it works. However entering/exiting play mode or any other rebuild of the ocean hierarchy loses the unpickability off the tiles.

Perhaps when the ocean hierarchy is constructed, the non-pickability shoudl be detected on the parent gameobject and propagated downwards.

**Versions**
Repro'd with BIRP, 2021.3.3f1

**Platform**
Editor / win64

**Comment by huwb** [comment]
Not a good start - simply querying pickability of the ocean using `SceneVisibilityManager.instance.IsPickingDisabled(ocean.gameObject)` seems to clear the pickability flag on the ocean when exiting playmode. 

It's as if the pickability state is left hanging after exiting play mode, and then querying it refreshes it to default (pickable).

**Comment by huwb** [comment]
Added a PR which may sort it. Will let Dale chime in when he's back

**Comment by daleeidd** [comment]
For anyone dropping by here, locking the water layer is another option: https://blog.theknightsofunity.com/hide-lock-layer-scene-window/

The only downside is if one has liberally used the Water layer elsewhere. Generally we only add the Water layer to the ocean tiles.
