### ISSUE TITLE
Ocean builder mesh memory leaks / shore line foam info

### ISSUE THREAD

**Issue by Revmatek** [wave-harmonic/crest#1064]
**Describe the bug**
Enabling and disabling the ocean renderer causes memory leaks. 

**Versions**
BRP

**To Reproduce**

1. Open "Boat Wakes" example scene. (also tested "main", but was not reproducible)
2. Select the OceanRenderer game object ("Ocean")
3. Rapidly enable / disable the OceanRenderer component
4. Observe in Task Manager memory steadily increasing over time (nothing too serious)
5. Optional: Using the new memory profiler https://docs.unity3d.com/ScriptReference/Profiling.Memory.Experimental.MemoryProfiler.TakeSnapshot.html
6. Take a snapshot of memory
7. Open the snapshot
8. Select the "Tree map" tab
9. Observe mesh data is populated by many "FAT", "FATX", etc (PatchType) mesh allocations with a single reference.

**Platform**
- Windows 11

**Additional context**
This was discovered when calling "Rebuild" in order to switch cameras to avoid a separate issue with shoreline foam no longer working when switching cameras. Each time the OceanRenderer is re-enabled it will create a new mesh which is never cleaned up by scene load (https://docs.unity3d.com/ScriptReference/Resources.UnloadUnusedAssets.html) This was in an older version, but I patched it with some of the other memory leak fixes I saw on here, and then verified that it does seem to be an issue in the main branch with a fresh install.

This seems to fix the memory leaks when added to OceanChunkRenderer, though I am unsure what the correct/desired fix would be in this case, it is at least a workaround.

```
        private void OnDestroy()
        {
            if (_mesh)
            {
                _mesh.Clear();
#if UNITY_EDITOR
                if (UnityEditor.EditorApplication.isPlaying)
                {

                    Destroy(_mesh);
                }
                else
                {
                    DestroyImmediate(_mesh);
                }
#else
                    Destroy(_mesh);
#endif
            }

            _mesh = null;
        }
```

**Comment by daleeidd** [comment]
Thanks for reporting. I made a PR which patches these leaks and several others.

If you'd like to open another issue for the foam if you believe it is bug then I can look at that too.

**Comment by Revmatek** [comment]
Thanks for the quick turn around. I will see if I can nail down some steps to repro in the example project for the foam.

**Comment by daleeidd** [comment]
Go ahead. Make as many as you need.
