### ISSUE TITLE
Sphere Water Interaction not working in standalone build

### ISSUE THREAD

**Issue by daleeidd** [wave-harmonic/crest#1098]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Have you checked the documentation to resolve your problem?

- [X] I have read the linked documentation and could not resolve my issue.

### Current Behavior

SWI work in the editor but not in a build.

### Unity Version

2020.3.40f1

### Crest Version

4.16

### Render Pipeline

Built-In

### Editor or Standalone

Standalone

**Comment by daleeidd** [comment]
SWI uses GPU instancing which will be stripped from builds if nothing else uses instancing. Scroll to _Using shader variants with GPU instancing_ in the following for instructions to prevent stripping:
https://docs.unity3d.com/Manual/gpu-instancing-shader.html

**Comment by mertboi** [comment]
I have the same issue, not working in build

**Comment by daleeidd** [comment]
Fixed in 4.17.
