### ISSUE TITLE
Updating ShapeFFT parameters runtime, generates a lot of garbage

### ISSUE THREAD

**Issue by powderek** [wave-harmonic/crest#1119]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Have you checked the documentation to resolve your problem?

- [X] I have read the linked documentation and could not resolve my issue.

### Current Behavior

Changing waves fields in runtime produces a lot of RenderTexture garbage e.g. ShapeWaves._waveDirectionHeadingAngle, ShapeWaves._windSpeed as shown in profiler below. Updating wind direction during gameplay is not possible because of this issue.

ShapeWaves._weight doesn't produce garbage.

![Unity_3n8EvFbpVx](https://github.com/wave-harmonic/crest/assets/19213882/6e924aac-903b-4af0-bbbd-39aee05146cd)
![Unity_ki0EWS0Y30](https://github.com/wave-harmonic/crest/assets/19213882/4cfe5e2f-6331-4318-b66b-f5a065e902dd)
![Unity_YgJDOEnhgV](https://github.com/wave-harmonic/crest/assets/19213882/b9008ae4-a049-47e5-9062-4cb365ca94b8)

### Steps To Reproduce

1. Create empty project with Crest.
2. Create empty scene.
3. Add OceanRenderer and ShapeFFT.
4. Change ShapeWaves._waveDirectionHeadingAngle in Update.
5. Observe profiler.

### Unity Version

2021.3.11

### Crest Version

4.17.3

### Render Pipeline

Built-In

### Editor or Standalone

Editor (Play Mode), Standalone

### Environment

```markdown
- OS: Windows 10
- GPU: RTX 3060
- Graphics API: Direct3D11
- Target Platform: Windows PC
```

**Comment by daleeidd** [comment]
Are you able to reproduce the issue by changing the same value through the inspector?

**Comment by powderek** [comment]
Yes, the issue still occurs when changing values through the inspector.

I actually found the problem in the code. In `FFTCompute.cs` there is method `GenerateDisplacements`. This method is checking if new values are different from previous values and if they are it is creating new generator with new render textures, without removing the old one. Memory allocation is piling up pretty quick and is leading to imminent crash. I fixed it for my case by changing some conditions but it would be good to see a generic global solution.

**Comment by powderek** [comment]
The problem doesn't exist in the main scene. I compared the setup and it turns out the problem happens only if Spectrum field on ShapeFFT component is left empty. If it is assigned then memory leaks doesn't happen.

**Comment by daleeidd** [comment]
Thank you for narrowing that down. Fixed with above commit.
