### ISSUE TITLE
HDRP underwater volumetric lights not working properly

### ISSUE THREAD

**Issue by Danon5** [wave-harmonic/crest#1121]
If you put a volumetric light under the water and crank up the volumetric multiplier so you can see it properly, the volumetrics will only appear on fragments that have a reasonable depth (i.e. when there are some objects behind the light). So, if you have no objects in your scene and do what I just described, no volumetric light will show at all.

This is a light that has some terrain behind it. The volumetrics appear properly.
![Screenshot 2023-05-30 053959](https://github.com/wave-harmonic/crest/assets/57692042/54921d9d-1885-4d67-a649-d88c4bdfca73)

This is that same light, but with the terrain hidden. The volumetrics are completely invisible.
![Screenshot 2023-05-30 054342](https://github.com/wave-harmonic/crest/assets/57692042/c8b6154c-5c35-4b91-a658-fe717a23c065)

I am using the default Fullscreen mode on the underwater renderer component.

_Originally posted by @Danon5 in https://github.com/wave-harmonic/crest/discussions/1120_

**Comment by daleeidd** [comment]
The underwater renderer is not compatible with volumetric fog in its current implementation. You might be able to workaround the issue using depth somehow without negatively affecting the fog. Perhaps an inverted sphere around the light.

**Comment by Danon5** [comment]
I will look into

**Comment by Danon5** [comment]
I will figure out a solution like that. Wasn't aware it was not supported. Will update the thread when I figure something out.

**Comment by Danon5** [comment]
(Didn't mean to reopen the thread) Wasn't aware it was not supported. I will look into a solution like that and comment on this thread if I find one.
