### ISSUE TITLE
Delayed LOD / tile enabling when using large clipping areas

### ISSUE THREAD

**Issue by Revmatek** [wave-harmonic/crest#1127]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Have you checked the documentation to resolve your problem?

- [X] I have read the linked documentation and could not resolve my issue.

### Current Behavior

When using a large `CrestRegisterClipSurfaceInput` the ocean tiles in the distance do not enabled when the camera returns to a angle where it would be able to see the ocean until a noticeable amount of time has passed.

Moving from below the clipping to above:
<img width="538" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/8ef0d0b1-7571-4c57-8eb3-9c2a0014cf6e">

Clipping should end here:
<img width="596" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/916ec101-167e-4c00-9d6a-6c6d4799f15a">

### Expected Behavior

Moving from below to above:
<img width="648" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/088ca31e-073d-453e-bb68-f569a73be427">

### Steps To Reproduce

1. Open the `BoatWakes` Scene
2. Create a large clipping area
<img width="452" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/3d08ab1f-ba40-4301-b463-a28a4d813de2">
<img width="905" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/be51e8ae-1a71-4799-8eaa-7673b35eaa91">

3. Hit play
4. Fly the camera up and down inside the clipping area
5. Observe that the camera disabled the tile at a certain height
6. Observe that the camera enabled the tile at a different height
7. Observe that the enabling of the tile seems delayed

Note: this can also be done in scene view

### Unity Version

2021.3.26f1

### Crest Version

4.17.3

### Render Pipeline

Built-In

### Editor or Standalone

Editor (Edit Mode), Editor (Play Mode), Standalone

### Environment

```markdown
- OS: Windows 11
```

### Anything else?

A workaround to this is to increase the LOD Count from 7 to 8. Reducing the LOD Count makes this appear with smaller clipping areas, definitely tied in some way, but it does not seem correct that the LOD is not enabled when it was at the same height prior to going down into the clipping area.

I am not sure this is a bug, but it seems like one, it may be intended based on the LOD count, the problem I see with this is inconsistency at which the tile is enabled / disabled. It seems like the visibility of tiles can be incorrect at times when rising out of the water.

To better illustrate this you can place a large cube / wall near the edge of the clipping and visible see the difference in enabling / disabled timing

<img width="410" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/b6d594f8-e34d-40f7-a920-152491432de0">

Video:

https://github.com/wave-harmonic/crest/assets/114962753/28c0815e-f72c-4e94-aaff-c908a6684bbe

Is there a way to adjust tolerance of the tile visibility beyond LOD?

**Comment by daleeidd** [comment]
Thanks for the detailed report! It was indeed a bug. LOD data should always blend out when nearing the end of the LOD chain. This isn't ideal as some configurability would be good but fixing it is good enough for now.

**Comment by Revmatek** [comment]
> Thanks for the detailed report! It was indeed a bug. LOD data should always blend out when nearing the end of the LOD chain. This isn't ideal as some configurability would be good but fixing it is good enough for now.

I took at look at this just now, and it does seem to fix the delay, however it also seems to introduce a problem where the clipping area is not longer respected and the tiles can appear inside the area when below:

Below:
<img width="557" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/0b330b0f-64f2-4278-9b92-569b4626dd61">

Above:
<img width="420" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/f9569133-ae94-46e4-bd5c-016c8523be02">

Its easier to see with a cube at the edge. Without the cube its hard to notice, but still happens.

**Comment by daleeidd** [comment]
That's expected. Default behaviour for all LOD data is to blend out between last set of tiles. A better approach would be to just prevent the data from bleeding over into the extents which is something I will look at doing in the future.

**Comment by Revmatek** [comment]
> That's expected. Default behaviour for all LOD data is to blend out between last set of tiles. A better approach for certain data would be to just prevent the data from bleeding over into the extents which is something I will look at doing in the future.

I think understand what you are saying. To clarify though, it still requires setting the LOD higher (7->8) in my case. To ramble on a bit, I cannot use the clipping areas if it shows inside the area because it would appear water is leaking through something such as a water dam / drydock. So I am ok just setting the LOD higher to fix it for my needs. I don't think there is a case where this would show correctly in such a scenario with this change, adjusting the LOD in some way or maybe like a flag... but maybe that wouldn't really help. I'm not really sure what the answer is, but blending by default (at least for me) will cause problems, it works fine with LOD set to 8 instead of 7, delay. I guess I was expecting it to work with LOD 7 since it appeared correctly previously but was delayed, now it will not appear correctly unless I use 8. But I am ok using 8 so maybe it is a nonissue, but it feels sorta like trade between it not showing one part vs another at LOD 7 and both require a higher LOD (maybe that is fine).

**Comment by daleeidd** [comment]
Yes, I understand the implications of the change.

Anyway, the future wasn't that far away as I have already done it.
