### ISSUE TITLE
Error of Does not exist some Classes.

### ISSUE THREAD

**Issue by yamanekaito0630** [wave-harmonic/crest#1133]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Have you checked the documentation to resolve your problem?

- [x] I have read the linked documentation and could not resolve my issue.

### Current Behavior

I purchased this asset from Unity Asset Store but I get some error:

`Assets/Crest/Crest/Scripts/Helpers/FloatingOrigin.cs(241,127): error CS0103: The name 'FindObjectsByType' does not exist in the current context`
`Assets/Crest/Crest/Scripts/Helpers/FloatingOrigin.cs(241,156): error CS0103: The name 'FindObjectsSortMode' does not exist in the current context
`
.....
`Assets/Crest/Crest/Scripts/Helpers/FloatingOrigin.cs(256,135): error CS0103: The name 'FindObjectsByType' does not exist in the current context`
`Assets/Crest/Crest/Scripts/Helpers/FloatingOrigin.cs(256,169): error CS0103: The name 'FindObjectsSortMode' does not exist in the current context`

I want to use this assets system.
What should I do? 
Thanks.

### Steps To Reproduce

1. Create New Project
2. Import this asset (Crest Ocean System)
3. End...

### Unity Version

2021.3.17f1

### Crest Version

4.19

### Render Pipeline

Built-In

### Editor or Standalone

Editor (Edit Mode), Editor (Play Mode), Standalone

### Environment

```markdown
- OS: Ubuntu 20.04.6 LTS
- GPU: NVIDIA Corporation GP104[GeForce GTX 1080]
- Graphics API: Vulkan
- Target Platform: Linux
```

**Comment by daleeidd** [comment]
Upgrade Unity to latest 2021 patched version.
