### ISSUE TITLE
FindObjectsSortMode

### ISSUE THREAD

**Issue by Xue1iang** [wave-harmonic/crest#1140]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Have you checked the documentation to resolve your problem?

- [X] I have read the linked documentation and could not resolve my issue.

### Current Behavior

1. Assets/Crest/Crest/Scripts/OceanRenderer.cs(1897,52): error CS0103: The name 'FindObjectsSortMode' does not exist in the current context
2. Assets/Crest/Crest/Scripts/OceanRenderer.cs(1897,24): error CS0103: The name 'FindObjectsByType' does not exist in the current context
3. Assets/Crest/Crest/Scripts/OceanRenderer.cs(1896,62): error CS0103: The name 'FindObjectsSortMode' does not exist in the current context
......

About 20 errors related to FindObjects

### Unity Version

2021.3.3f1

### Crest Version

4.19

### Render Pipeline

High Definition

### Editor or Standalone

Editor (Edit Mode)

### Environment

```markdown
- OS:Ubuntu 20.04
- GPU:RTX 3060
- Graphics API:Vulkan (1.2.131.1+dfsg1-1)
- Target Platform: PC
```

**Comment by Xue1iang** [comment]
Problem solved

**Comment by daleeidd** [comment]
For anyone else... always use the latest patched version of Unity.

**Comment by daleeidd** [comment]
We reverted usage of these APIs in 4.20.1 so should no longer be a problem.
