### ISSUE TITLE
Enable Shader API does not function without changing underwater appearance 

### ISSUE THREAD

**Issue by Revmatek** [wave-harmonic/crest#1145]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Have you checked the documentation to resolve your problem?

- [X] I have read the linked documentation and could not resolve my issue.

### Current Behavior

Enable Shader API moves the command buffer to/from before/after forward alpha which enables transparent shaders to render after the fog. While this is desirable, it does not seem like it works with the rest of the features (the docs say this is in "Preview This feature is in preview and may change in the future.")
`_camera.AddCommandBuffer(_enableShaderAPI ? CameraEvent.BeforeForwardAlpha : CameraEvent.AfterForwardAlpha, _underwaterEffectCommandBuffer);`

I have been unable to use this feature because it alters the appearance of the surface / underwater rendering while in an ocean environment, not a mask / contained area with limited settings or short view distance.

### Expected Behavior

Enabling the Shader API should not alter the appearance of the ocean shader, lighting, or create artifacts.

### Steps To Reproduce

1) Open Main.unity
2) Play
3) Go underwater
4) Turn on the shader api
5) Adjust settings to see a bit further
<img width="439" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/a1b6e842-705d-492e-8644-e710ec5096e0">

6) Observer on / off behavior of shader api

Off:
<img width="920" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/5f895726-fa0b-4429-8159-28a5aebc2cee">

On:
<img width="874" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/aa335326-72e8-4daf-8417-2f2339593f89">

### Unity Version

2021.3.26

### Crest Version

4.19

### Render Pipeline

Built-In

### Editor or Standalone

Editor (Edit Mode), Editor (Play Mode)

### Anything else?

You can sorta work around the API problem by using custom rendering for transparent shaders that have issues using the command buffer and not using the Enable Shader API feature. This does not always work though nor is it desirable.

**Comment by daleeidd** [comment]
These are two separate issues if you could kindly make a new one for one of the issues.

**Comment by Revmatek** [comment]
> These are two separate issues if you could kindly make a new one for one of the issues.

I am not really sure which two separate issues you mean specifically of the various problems with the shader API mentioned. The primary issue is that the Shader API is non-functional any other information I have provided is for context. I can update the title to more accurately reflect the problem.

**Comment by Revmatek** [comment]
There may be several distinct problems here, but I am not sure where the lines are or if they are all the same thing.

1) Support for transparent shaders underwater does not seem to work because other things stop working (it does actually allow transparency with the underwater fog)
2) Artifacts appear, which I did not originally know, I included it here because I noticed it when I went to make sure it was reproducible in the demo scene.
3) Lighting on the surface appears to change
4) The transparency on the surface of the water looks different

Do you want me to create 4 issues? I am fine if you break this up however you need to and I can sub to the other issues.

**Comment by daleeidd** [comment]
Making a new issue for the artefacts should be enough.

**Comment by Revmatek** [comment]
> Making a new issue for the artefacts should be enough. 

I have create this issue https://github.com/wave-harmonic/crest/issues/1146

> The other issues are tied to Depth Fog Density Factor?

I don't think it is required, I did that to help illustrate the extreme difference in appearance. For my settings you can see far underwater so it is immediately apparent when enabled because it changes all the visuals of the underwater perspective and makes it harder to see the surface. I did confirm that without changing the setting is still occurs by examining the shader example in the example scene where it is masked as a sphere, you can zoom in on it and look around underwater and toggle the api and see the same visual changes, it is just much more apparent when you can see a bit further in the fog how much it affects everything.

**Comment by daleeidd** [comment]
Thanks.

It looks like the Depth Fog Density Factor and the portals feature currently do not work with the Shader API. I was unable to see any differences when either of these are not used.

Does this sound correct? If it affects it without those features used, can you provide an example?

**Comment by Revmatek** [comment]
> Thanks.
> 
> It looks like the Depth Fog Density Factor and the portals feature currently do not work with the Shader API. I was unable to see any differences when either of these are not used.
> 
> Does this sound correct? If it affects it without those features used, can you provide an example?

That does sound correct in terms of Depth Fog Density Factor. I may be able to get the visuals I want by directly modifying Depth Fog Density vs Depth Fog Density Factor. It was not clear to me this transparency was independent of the surface (though maybe that was not intended) I will have to investigate a new implementation though.

I am not currently concerned with portals so I have no information on that.

I played around with it at runtime and it looks the same on/off in the demo main scene. I tried this in my setup as well and I only see very minor differences, I will have to investigate them though with a task to refactor how the underwater stuff works to accommodate this new information (unless you have an easy fix to make these features play nice).

Here is what I see if it is helpful, there may be other settings at play though. Ignore any floating particles or jellyfish you see in terms of transparency, the support I added for them underwater does not work with me toggling the API back and forth.

Original with Depth Fog Density Factor in play:
![image](https://github.com/wave-harmonic/crest/assets/114962753/a53930d0-ef72-4400-b2d9-287d6a42582c)

Manually tweaking shader values at runtime Factor = 1 (which I assume is what you mean by disable):
![image](https://github.com/wave-harmonic/crest/assets/114962753/cbb744cc-6e21-4a68-b7ef-0700aed2c38d)
So far near identical... 

Enabling shader API with Depth Fog Density changes on the shader:
![image](https://github.com/wave-harmonic/crest/assets/114962753/2aa6c813-959d-4cb3-90a5-c6b3fa064c5c)
Now I do start to see some differences in the distance where the transparency is near the geometry of the ocean tiles and the docs I have in the image on the left.

It is more apparent in the shadows

Off:
![image](https://github.com/wave-harmonic/crest/assets/114962753/3eb32eef-2cb3-4092-8b90-33eb072a43e6)

On:
![image](https://github.com/wave-harmonic/crest/assets/114962753/3981d8fb-54a0-4dd7-bd39-94f0aaadaba9)

Off:
![image](https://github.com/wave-harmonic/crest/assets/114962753/c87ef46b-a8d8-4073-b0f8-3354247dc992)

On:
![image](https://github.com/wave-harmonic/crest/assets/114962753/8ebd078f-1c87-44ab-b54c-7ab943362f96)

This also changes the surface from above to be near non existent, extremely transparent, not what I am going for. The settings in the main scene are different and seem darker so you can't see very far still and there is nothing out there to render over, not really sure the differences.

Normal:
![image](https://github.com/wave-harmonic/crest/assets/114962753/9789c7a8-2c45-4ab6-9118-fb95cdca942d)


Shader changes / Factor 1:
![image](https://github.com/wave-harmonic/crest/assets/114962753/eb059c88-79f6-453d-b9f8-d5ca44218c41)
Not really ok. So not something I can work around with I guess. The primary issue is that Depth Fog Density Factor is not working with the Shader API as you described.

**Comment by Revmatek** [comment]
If you play around in the boat wake scene you can sort see some of the differences:
Off:
![image](https://github.com/wave-harmonic/crest/assets/114962753/a01f6187-84e1-4911-b57f-46a58720202a)

On:
![image](https://github.com/wave-harmonic/crest/assets/114962753/123fcbc3-6432-49d7-ad26-65a1f8a245d4)

It is sorta difficult to see with these screenshots even side by side, you really need to switch back and forth to see the differences. Though I have lowered the density to an extreme here to obtain the desired affect. 0.01

**Comment by daleeidd** [comment]
Thanks. That should be all fixed now with latest.

**Comment by Revmatek** [comment]
> Thanks. That should be all fixed now with latest.

I will check it out.

**Comment by Revmatek** [comment]
The water surface definitely looks correct now with Shader API enabled.

I am noticing a couple issues with a lowered Depth Fog Density which I can repro by changing settings in the main scene
![image](https://github.com/wave-harmonic/crest/assets/114962753/6dd6c443-bc4a-4f10-b3cb-40dc19656a68)

Shader API Off:
![image](https://github.com/wave-harmonic/crest/assets/114962753/d2cd2ef3-a18f-445f-9ddf-d88c8082afed)

On:
![image](https://github.com/wave-harmonic/crest/assets/114962753/6d6c288b-7345-4eee-b339-47014ef4d861)
These 2 white lines are a tile being culled very close when shader api is on, but it does not do so for off.
![image](https://github.com/wave-harmonic/crest/assets/114962753/fb178180-3006-4902-9f17-437b72ccd6ea)
It is much more apparent in my setup, I am trying to determine the differences. The surface lighting seems to be an issue with my version of the ocean, maybe I am missing a commit or something recent. The tile culling does seem like a problem with latest though.

Both On:
![image](https://github.com/wave-harmonic/crest/assets/114962753/cdea5b6f-4b9b-4652-9d7c-520125144c5f)
![image](https://github.com/wave-harmonic/crest/assets/114962753/98dfad74-1b20-4b90-8910-9bff31a77acc)

**Comment by Revmatek** [comment]
I am very perplexed by what I am seeing. I cannot seem to determine the cause of the lighting change. I went so far as to re-integrate with the crest project where the lighting change does not occur. As far as I can tell all the code is the same (with the exception of things that are changed that are not running in the demo scene, like 3rd party fog, even taking that out has no effect). It almost seems like there is something stuck somewhere. I can copy the entire scene to the working project and everything works fine without changes...

Demo scene in my project:

Off:
![image](https://github.com/wave-harmonic/crest/assets/114962753/873b70c7-b4ee-432c-a2a6-a8100b3e283c)

On:
![image](https://github.com/wave-harmonic/crest/assets/114962753/8873e3bb-f94b-4ef7-9eee-a775cf1b6a40)

**Comment by Revmatek** [comment]
Rebuilding the library has no effect on the lighting problem, however disabling the directional light in the scene and creating a new one completely eliminates the lighting problem. It is not clear to me why. Must be some sort of corruption, if it was corrupted it should not have worked when loaded into another project. If I duplicate the light in the scene it remains broken.

Off:
![image](https://github.com/wave-harmonic/crest/assets/114962753/214b2924-87ca-4e6b-bbbf-f012e6ad8e2f)

On:
![image](https://github.com/wave-harmonic/crest/assets/114962753/904d44f6-0a45-4cf5-a537-917d1b0f4201)

Wonderful!

I'm not really sure what to make of this, but I have seen this happen before with lights being corrupted somehow. Idk if that means I need to destroy mine and make a new set with the same settings and everything will work then. Some sort of bug.

So the tile culling is the only thing that remains maybe.

**Comment by Revmatek** [comment]
It is working though (minus the tile culling), I will have to test this out in my next build, I have other issues I need to address first.

close to defaults:
![image](https://github.com/wave-harmonic/crest/assets/114962753/a1f387e7-ebaa-46c9-8912-97c0bad60944)

lower depth fog density factor:
![image](https://github.com/wave-harmonic/crest/assets/114962753/a6e2c203-f6d1-40fc-8318-559596c6549b)
![image](https://github.com/wave-harmonic/crest/assets/114962753/d10fded8-6e72-46a4-ab69-4ab9cdf1e6f9)

**Comment by Revmatek** [comment]
It seems that the act of changing the color of the light causes this issue. But only in this project... Does not occur in latest project, which is the same code as I mentioned early. 

![image](https://github.com/wave-harmonic/crest/assets/114962753/d7c5f3a9-1cd3-4f82-b008-2a2ffad9030b)

![image](https://github.com/wave-harmonic/crest/assets/114962753/dc74b877-f2cf-49af-bbef-e29545b712ad)

**Comment by Revmatek** [comment]
It appears to be caused by the color space settings in the project, it works with Linear but not Gamma.

**Comment by daleeidd** [comment]
Latest has it fixed for gamma. The line issue is probably related to #1146 instead?

**Comment by Revmatek** [comment]
> Latest has it fixed for gamma.

Fix looks good! I will check it out more when I implement it later. 
![image](https://github.com/wave-harmonic/crest/assets/114962753/c1a91d15-1913-4eca-bd67-9d9fef353c85)


> The line issue is probably related to #1146 instead?
I think this is a separate issue as it occurs because a tile is missing, not from a horizon artifact of some sort. It happens with MSAA off and 
![image](https://github.com/wave-harmonic/crest/assets/114962753/52347ab2-a394-45e0-8cd3-70f147afe352)

![image](https://github.com/wave-harmonic/crest/assets/114962753/68efdc0d-149d-4f57-8c1e-447639556036)
![image](https://github.com/wave-harmonic/crest/assets/114962753/2a0e5a9e-54a9-4505-bdfe-c6cde93305a5)

It is difficult to get a good look at what it is, but I am fairly certain it is some sort of tile gap
![image](https://github.com/wave-harmonic/crest/assets/114962753/c7d8dc2d-8ba5-4dc2-80bd-6f1972ba2ccc)
![image](https://github.com/wave-harmonic/crest/assets/114962753/adeb1804-085e-4609-8ef7-4768fafc1d28)
![image](https://github.com/wave-harmonic/crest/assets/114962753/98efedce-f46f-443c-999a-567af90b09d6)
![image](https://github.com/wave-harmonic/crest/assets/114962753/637c8866-fa7a-44a8-9223-f31f66effd56)
![image](https://github.com/wave-harmonic/crest/assets/114962753/35a33b16-37cd-406c-a03a-2b8def55f3c1)
Disabling it manually
![image](https://github.com/wave-harmonic/crest/assets/114962753/dd7a0ea0-df75-41d2-b959-cd1d0923a9c5)
![image](https://github.com/wave-harmonic/crest/assets/114962753/1cf0cc4c-add2-4efb-a856-8b34180f7021)
I cannot observe it up close when paused
![image](https://github.com/wave-harmonic/crest/assets/114962753/1d7097c4-a3a2-4d4e-8c87-abc1f9a1a439)
Camera perspective
![image](https://github.com/wave-harmonic/crest/assets/114962753/1c7cf6c5-cd28-4615-a7ac-303ec8711372)
![image](https://github.com/wave-harmonic/crest/assets/114962753/3593f19f-b9da-4fc4-bb94-76b1876b3a95)
Requires a certain angle
![image](https://github.com/wave-harmonic/crest/assets/114962753/6a68a291-e633-4175-b185-58b58e5ab334)
![image](https://github.com/wave-harmonic/crest/assets/114962753/5e9c6214-03b8-4a85-ae6a-44f8270985de)

Having said all that I don't see that in my project, only the example scene (which means I may see it later)

Side note:
I do see the bounds of the ocean tiles being culled on the sides of the screen though, which I fixed in my scene by increasing the size of the tile renderer bounds arbitrarily. 
![image](https://github.com/wave-harmonic/crest/assets/114962753/7eb7789c-d6b4-4334-9833-020c449275b3)
![image](https://github.com/wave-harmonic/crest/assets/114962753/49404e07-667a-44b6-be10-f7ffb5a5d823)
This can manifest to more extremes when above the ocean, just an FYI. I may have mentioned previously, I don't recall where.

**Comment by Revmatek** [comment]
I am still seeing an issue with shadows when shader api is on, you can recreate this in the main scene by adding a giant cube above the water or other object that should make the water dark.

Off:
![image](https://github.com/wave-harmonic/crest/assets/114962753/c455d7ad-b38e-4c52-ab35-9ab73d34a3cd)
![image](https://github.com/wave-harmonic/crest/assets/114962753/771640cb-f3f1-44a9-81bf-180b45f4ede4)

On:
![image](https://github.com/wave-harmonic/crest/assets/114962753/cf063cd2-264e-4dfb-83cb-bf0a62df8e12)
![image](https://github.com/wave-harmonic/crest/assets/114962753/2585513d-f011-443e-84e8-bdf43510627a)

This is what appears to be causing shadow / lighting issues with the docks in the images above

On:


Some other thoughts on this, I may need to disable tiling culling or something to prevent transparent objects over the ocean from becoming visible when tiles are culled. When the tiles are culled it seems more like objects above the surface (clouds or smoke for example) become part of the ocean because they are not longer masked by the surface.

ON:
![image](https://github.com/wave-harmonic/crest/assets/114962753/f6711938-f88e-4600-a032-b41b38925eb3)
Off:
![image](https://github.com/wave-harmonic/crest/assets/114962753/dc0e967a-e240-47a3-b9d9-c77d9c92a8e1)

**Comment by daleeidd** [comment]
I will look at the shadow one but fixing it requires recalculating the scattering term a second time which could be a bit of a performance hit.

In regards to culling, please open new reports for separate issues to reduce noise in this one.

And yeah that makes sense re disabling underwater culling.
