### ISSUE TITLE
Planar Reflections issue with non-standard shaders using transparency 

### ISSUE THREAD

**Issue by Revmatek** [wave-harmonic/crest#1147]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Have you checked the documentation to resolve your problem?

- [X] I have read the linked documentation and could not resolve my issue.

### Current Behavior

Planar reflections texture does not show custom shaders / transparency. It may be custom shaders in general if I recall. I think it works for most standard shaders.

Note: that the palm leaves are not visible in the reflection.
![image](https://github.com/wave-harmonic/crest/assets/114962753/fb36bc0f-11a2-4f95-9f11-60facc2cbb18)

My primary concern for this is the tree leaves not showing up. This example has hidden shaders on the tree which I cannot redo easily. The example light blue cube is something I can modify to add support if that is possible.

### Expected Behavior

There should be some sort of way to add support for transparency in custom shaders (seems to work fine for Standard Shaders with transparency, which may exclude all forms of tree shader)

### Steps To Reproduce

1) Create a scene with Planar reflections
2) Add some objects using custom shaders and transparency or Speed Tree (or similar Tree Creator shader)
3) Observe missing reflections
![image](https://github.com/wave-harmonic/crest/assets/114962753/2393a7f5-5132-407b-91d7-76ab24a568ec)

### Unity Version

2021.3.26

### Crest Version

4.19

### Render Pipeline

Built-In

### Editor or Standalone

Editor (Edit Mode), Editor (Play Mode), Standalone

### Anything else?

Filling this out here while investigating other issues, this was in my backlog, not terribly important but probably a bug somewhere. I investigated it a one point and ended up in a shader somewhere that was applying transparency to the planar reflection texture or something... I don't recall the specifics. I am not sure if there is some workaround to this I am unaware of, something I need to add in the shaders perhaps.

**Comment by Revmatek** [comment]
> Does changing the _Clear Flags_ to _Skybox_ solve it?

Changing the Clear Flags does not seem to have an effect. The clear flags for the image above is with Skybox.

**Comment by daleeidd** [comment]
Is that on the OceanPlanarReflections script? Otherwise can you remove the ` * saturate(refl.a)` from the following line:
https://github.com/wave-harmonic/crest/blob/0be7cca7660b44150ec2321825565ed626896b4a/crest/Assets/Crest/Crest/Shaders/OceanReflection.hlsl#L29

**Comment by Revmatek** [comment]
> OceanPlanarReflections

This is OceanPlanarReflections script, yes. Disabling saturate does have an effect and makes the tree leaves appear, but causes other more obvious problems with reflections / darkness on the surface
![image](https://github.com/wave-harmonic/crest/assets/114962753/c899c6f9-8747-4ba9-aa12-6d6bf5b53faf)
![image](https://github.com/wave-harmonic/crest/assets/114962753/6669671f-5a61-4c1f-ab69-7d9a87105ebe)

**Comment by daleeidd** [comment]
That image looks like _OceanPlanarReflections > Clear Flags_ is not set to Skybox. Unless your skybox does not write alpha which would be strange. Try testing with Unity's procedural skybox.

**Comment by Revmatek** [comment]
> That image looks like _OceanPlanarReflections > Clear Flags_ is not set to Skybox. Unless your skybox does not write alpha which would be strange. Try testing with Unity's procedural skybox.

It seems unrelated to the skybox. I tried it with default and a few others. Doesn't change. It also does not seem related to OceanPlanarReflections being on
![image](https://github.com/wave-harmonic/crest/assets/114962753/ba575dfd-56f6-49d5-83ac-a1f6f83bf91a)

**Comment by daleeidd** [comment]
Can you provide a screenshot of the OceanPlanarReflections?

**Comment by Revmatek** [comment]
> Can you provide a screenshot of the OceanPlanarReflections component?

![image](https://github.com/wave-harmonic/crest/assets/114962753/1e9b71fb-dc6b-4648-ab33-1c19cd3b7a72)

**Comment by Revmatek** [comment]
> Can you provide a screenshot of the OceanPlanarReflections component?
Well I guess that solves that mystery. I was not aware you were referring to Clear flags on this script vs the camera.
![image](https://github.com/wave-harmonic/crest/assets/114962753/616175af-2b22-4a41-b4f7-404f6725dd5f)
![image](https://github.com/wave-harmonic/crest/assets/114962753/cfa14e48-9f18-4008-8f0b-84e5834d4021)

![image](https://github.com/wave-harmonic/crest/assets/114962753/d0fe8db9-997e-4fb3-b9e7-33608c1d9f3e)

**Comment by daleeidd** [comment]
No worries. Does it work correctly if you remove the reflection alpha modification?

**Comment by Revmatek** [comment]
> No worries. Does it work correctly if you remove the reflection alpha modification?

Yes, it does appear to be working correctly now.

![image](https://github.com/wave-harmonic/crest/assets/114962753/00958f33-1f9f-4658-a3cf-27a43c934e9d)
It does seem to wash out a bit after I stop moving the camera but it is mostly fine. Definitely an improvement.
![image](https://github.com/wave-harmonic/crest/assets/114962753/016a1982-62e1-4d5e-9eb8-448c69732c36)

Seems to depend on the angles and only with trees
![image](https://github.com/wave-harmonic/crest/assets/114962753/732231e6-b05c-451b-ab7d-1cace85c4ad4)
![image](https://github.com/wave-harmonic/crest/assets/114962753/2d34246c-4014-4704-9d77-c94616d91ec1)

I'm not sure why there is a distinction between the transparency in the standard shaders and the custom / tree shaders, obviously depends on what each shader is doing I guess.

**Comment by daleeidd** [comment]
Perfect. That could be a combination of fresnel and colours blending.

I'll make Skybox the default as prefer to have things work over an optimisation. I'll document this in the tooltip and somewhere in the documentation too.

**Comment by daleeidd** [comment]
Fixed in 4.20.

**Comment by Revmatek** [comment]
@daleeidd I was able to completely eliminate the washing out by doing the following:

Line 269:
```
ClearRenderTexture(_reflectionTexture);
_camReflections.Render();
```
```
public void ClearRenderTexture(RenderTexture renderTexture)
{
    var previousRenderTexture = RenderTexture.active;
    RenderTexture.active = renderTexture;
    //do not over saturate transparent shaders
    GL.Clear(true, true, Color.black);
    RenderTexture.active = previousRenderTexture;
}
```

I am not 100% on the issue or if this is the best fix, but it seems like when the transparent shader is being rendered, every time it refreshes and renders again it is overdrawing on the previous transparent color (which may be why it appears washed out / over saturated). I noticed it did not occur if I reduce the refresh rate (which has other obvious drawbacks)

Here is the difference this makes (it is more apparent in the dark):

### Without clearing
![image](https://github.com/user-attachments/assets/d077ed0d-af23-40ae-be04-1f8bff65c5eb)
![image](https://github.com/user-attachments/assets/61d06f4b-532a-4cf1-b934-43571a232499)

### With clearing
![image](https://github.com/user-attachments/assets/5c9fe227-9abe-4e50-8d16-41f9dfd7b198)
![image](https://github.com/user-attachments/assets/c78d9727-d7ea-4fdc-a8ee-07431f5cdfa4)

It seems much better and as far as I can tell everything else is the same.

**Comment by daleeidd** [comment]
Thank you. I will look at this further for next release.
