### ISSUE TITLE
[Quest] Underwater View displayed above Waterline and no underwater view below Waterline

### ISSUE THREAD

**Issue by MR-Alex42** [wave-harmonic/crest#338]
**Describe the bug**
Underwater View displayed above Waterline and no underwater view below Waterline.
This seems to happen if camera is looking at a sharp angle at the water surface. 

**Screenshots / videos**
Screenshot from Quest:
![image](https://user-images.githubusercontent.com/15617301/64784747-15795180-d56b-11e9-9248-277e3a4fdee4.png)
![image](https://user-images.githubusercontent.com/15617301/64784757-1ca05f80-d56b-11e9-9099-597585666246.png)

For comparison a screenshot from the editor:
![image](https://user-images.githubusercontent.com/15617301/64785474-bd434f00-d56c-11e9-9c6c-62bf2d9484a2.png)

**Log**
No errors shown in Log.

**Versions**
Render pipeline : Built-in
Unity: 2019.1.2f1

**To Reproduce**
Can provide project and APK if helpful.
Will add a download link later.

**Platform**

Android
Hardware
Oculus Quest (Snapdragon 835 chipset, Adreno 540 GPU, 4 GB RAM.

**Additional context**
This has underwater enabled with UnderWaterCurtainGeom and UnderWaterMeniscus attached to LeftEyeAnchor and RightEyeAnchor. Works fine in Editor. I used multipass as stereo rendering mode in the XR settings. Forward rendering pipeline.

**Comment by huwb** [comment]
Apologies we haven't managed to look at this, all our resources have gone into supporting the paid versions of crest recently and preparing for future versions.

There was a recent issue which seems very similar to this: #367 . Not sure if its related but thought i'd mention in case the same fix applies to this.

**Comment by daleeidd** [comment]
Thanks for reporting. Going to close as the _Underwater Renderer_ has since been introduced which works.
