### ISSUE TITLE
[LWRP/UniversalRP] UnderwaterEffect is broken on Vulkan 

### ISSUE THREAD

**Issue by EliGould** [wave-harmonic/crest#367]
**Describe the bug**
When moving the camera underwater in e.g. one of the example scenes, it glitches between showing the undewater effect and not. The underwater effect can remain, even when the waves move below the player height.

The caustics also appear to be quite choppy and don't blend in smoothly.

**Screenshots / video**
![PirateCove_Original](https://user-images.githubusercontent.com/15649355/69332185-70f44980-0c56-11ea-94c2-320e4c960a8e.png)
![PirateCove_1](https://user-images.githubusercontent.com/15649355/69332108-44d8c880-0c56-11ea-908c-ce0017f0a0b2.png)
![PirateCove_2](https://user-images.githubusercontent.com/15649355/69332109-44d8c880-0c56-11ea-9fc4-eb19b197cf9e.png)

[CrestUnderwaterBug_Short.zip](https://github.com/crest-ocean/crest/files/3874284/CrestUnderwaterBug_Short.zip)

**Log**
No error or warning is shown in the log. 

**Versions**
Unity 2019.3.0b7 
Universal Render Pipeline 7.1.5
Crest 3.1

**To Reproduce**
Enter the PirateCove-Day scene and move the slowly camera under water. No underwater effect should be visible. Look up to trigger the underwater effect. Move slightly above the waves to see the underwater effect remain, even with the waves visible below you now. 

**Platform**
Windows Editor with Vulkan as Rendering API

**Hardware**
GPU: NVIDIA GeForce RTX 2060
CPU: Intel Core i5-9400F

**Comment by EliGould** [comment]
I'm sorry, I accidentally already submitted the issue while filling it out. I will add the proper information right away.

**Comment by huwb** [comment]
Hello, apologies you ran into this. Thanks for filling out the above.

I did a few tests and got the same behaviour - it seems to be broken on Vulkan for me as well, so something is wrong. I'll let you know when I have news, hopefully by this weekend.

**Comment by huwb** [comment]
I messed around a bit more - it seems to be a crazy driver bug that doesnt make any sense :/.

Could you try replacing your Crest\Shaders\Underwater\UnderwaterShared.hlsl with the attached. I unrolled the loop and apparently that seems to fix it..

[UnderwaterShared.zip](https://github.com/crest-ocean/crest/files/3877053/UnderwaterShared.zip)

**Comment by EliGould** [comment]
Thank you for looking into this so quickly.  Such a weird bug.
So I tested the shader with unrolled loop and it seems a bit better but it still shows all of the same symptoms. This occurs a lot less but it can still happen if you are right above the water line:
![PirateCove_1](https://user-images.githubusercontent.com/15649355/69407653-55944780-0d05-11ea-93cf-d0ef85cc09e9.png)

I still get plenty of this:  
![PirateCove_0](https://user-images.githubusercontent.com/15649355/69407679-6775ea80-0d05-11ea-9c5c-75063d7d2aac.png)

The underwater effect itself seems to work a bit better but it still bugs out a lot, either not being activated at all or flickering between on/off when moving. I might be wrong but I feel like it is worse close to the shore. 

No rush with this issue, at least not from my side. It currently doesn't block me from what I am working on.

**Comment by huwb** [comment]
Sorry for such a long delay. Had another look now, in win64 editor and vulkan. URP / Unity 2019.3.3

I flew around with a half submerged camera for a while but wasn't able to get the above to happen (no flicker or odd appearance like your screenshot shows).

We had a case where we had a constant buffer collision in vulkan. It meant that shader parameters could overwrite eachother and produce weird/random results. It was found when the waves looked broken (#359) but its possible it could affect underwater i guess. 

Are you encountering this still, and if so what versions of things are you on?

**Comment by daleeidd** [comment]
Thanks for reporting. Going to close this one as we have introduced the Underwater Renderer which probably doesn't have this issue. Please reopen if you do continue to experience the problem with that.
