### ISSUE TITLE
Walkable submarines with portholes to look out

### ISSUE THREAD

**Issue by valentinwinkelmann** [wave-harmonic/crest#376]
Hi guys, I'm currently working on a diver game and here crest seems to be just the ideal solution due to its clean transition between the above water and under water world.
Now I wonder if it is possible to exclude a completely walkable submarine or an underwater station from underwater rendering so that it is possible to move inside and look out through glass windows, portholes etc and look into the ocean.

Also important would be to look out of windows during a "half dive" so that e.g. a porthole is only half underwater.

is this already possible with cest? are there any examples?

**Comment by huwb** [comment]
Hello,

This is not super-possible out of the box. I think its possible, but would need some coding, currently. I think this discussion is related and would be worth looking through: https://github.com/crest-ocean/crest/issues/77

**Comment by huwb** [comment]
I'll close this out as I think #77 is the best place to discuss further.

However, I have noted how many times this request has come up lately, and will add it to our internal trello to look at making this supported out of the box in the next months.

**Comment by daleeidd** [comment]
Just adding that #462 is a work-in-progress towards providing this feature. It has been put on hold for the time being.

**Comment by huwb** [comment]
This is still on the list, and something we're keen to do, but we dont have a timeline on it. We don't have bandwidth to work on more than one or two new features at a time. But we are slowly getting closer to picking this up..

We're hoping to increase our bandwidth through sponsorship and i wanted to mention that once here in case there is interest in supporting us: https://github.com/sponsors/wave-harmonic

**Comment by daleeidd** [comment]
This has been implemented as the _Portals and Volumes_ feature with #960. It was released with 4.15 so I will be closing this issue.
