### ISSUE TITLE
Allow runtime wave direction changes

### ISSUE THREAD

**Issue by chrispewebb** [wave-harmonic/crest#403]
Currently it is not possible to smoothly rotate the direction of the waves (to make them match the direction of wind that changes at runtime, for example).

This would be an extremely useful feature.

**Comment by huwb** [comment]
There is a way which is functional if not elegant.

It's possible to smoothly blend between two wins directions by having two gerstner scripts with different wind angles and cross fading their weights. It should be possible to generalise this to arbitrary wind directions by driving these angles and weights from s script.

I think it would be possible to push this functionality down so the cross-fading is automatic and I hope to look at this soon, I'll leave this open.

**Comment by huwb** [comment]
Took a little longer than planned (!!) but this works with the new *ShapeFFT* component now that #853 merged.
