### ISSUE TITLE
Dynamic Waves Appear to be tied to FPS

### ISSUE THREAD

**Issue by holdingjason** [wave-harmonic/crest#408]
**Describe the bug**
The amount of dynamic wave distortion you get ala strength seems to be tied to frames per second.  Decrease the frames and you get less distortion, increase frames more (not sure if the increase is ultimately capped by whatever your settings are and that you only see the correct distortion at a very high framerate ala 100+ etc)

**Screenshots / video**
These are very helpful to understand and diagnose issues.

**Log**
What is in the editor log? Clear before running and then provide any errors/warnings that appear. The log frequently provides the key hints.

**Versions**
Which render pipeline (built-in/LWRP/HDRP)? Which version of LWRP/HDRP? Which version of unity (including minor, i.e. 2019.1.0f2)? 

**To Reproduce**
How can the developers reproduce this bug? Are you able to reproduce the issue in the example content/scenes?  Yes.

Please include steps to reproduce the behaviour, with the example content ideally so we can follow the steps on our side.
Using the boat demo you can easily repro this by just creating a script that changes the overall frame rate, so spit out a bunch of debug statements in a loop for instance but does not matter anything to control the current FPS.

**Platform**
Editor or Build.  PC

**Hardware**
ATI Radeon RX 580

High FPS 88+
![image](https://user-images.githubusercontent.com/42001313/73138355-856a0f00-4016-11ea-9612-6d6539ac0702.png)

Low FPS 30 or so.
![image](https://user-images.githubusercontent.com/42001313/73138329-3cb25600-4016-11ea-8c46-a8bcfffbfa5b.png)

**Comment by holdingjason** [comment]
BTW if you look at the two shots one thing that jumps out is the sim steps are different 3 to 2.

**Comment by huwb** [comment]
Thanks for the comparison, really useful. I'll let you know when we have news.

Btw the step count will be different as a result of the framerate being different, this is expected for fixed timesteps.

**Comment by holdingjason** [comment]
Thanks @huwb let me know if I can help in anyway since this is a pretty nasty one so happy to help.  Still might be something I am doing but since I was able to see it in the demo hoping not :)

**Comment by iichiversii** [comment]
Creating bow and stern dynamic waves is something I cant setup, can someone make a video tutorial on this?

**Comment by moosichu** [comment]
@iichiversii I would ask on the Discord server for questions to that kind of thing: https://discord.gg/g7GpjDC

**Comment by Epimolophant** [comment]
Hi! Any news on this?

**Comment by huwb** [comment]
I have a test/experimental PR which locks simulation rate, which should help with this. feedback welcome

https://github.com/crest-ocean/crest/pull/734

**Comment by huwb** [comment]
Will be fixed in 4.9

**Comment by daleeidd** [comment]
Thanks for reporting. 4.9 has been released which solves this issue. The simulation may produce different results so tweaking may be required. Let us know if it can be improved.
