### ISSUE TITLE
Ocean Underwater Effect with Lens Shifted Camera in Unity

### ISSUE THREAD

**Issue by generalsofttr** [wave-harmonic/crest#427]
When a lens shifted camera (Camera --> Physical Camera --> Lens Shift --> X --> give any value) is used in project Underwater Effect disappears.

Below :
 first screenshot is from a normal camera ( main crest example scene, democamera)
second screenshot is taken from when lens shift value of the camera changed to 1

![001](https://user-images.githubusercontent.com/60553205/75609434-8d3b3880-5b19-11ea-9ecf-291f19bbad70.PNG)

![002](https://user-images.githubusercontent.com/60553205/75609437-8f9d9280-5b19-11ea-9288-07369636a4b5.PNG)

![003](https://user-images.githubusercontent.com/60553205/75609439-94fadd00-5b19-11ea-9724-31550546c9a6.PNG)

**Comment by moosichu** [comment]
We have been able to reproduce the issue. This will be treated as low-priority for now as we have some other problems to tackle.

However, we have a branch with a different underwater implementation:
https://github.com/crest-ocean/crest/pull/299

This branch doesn't have this issue so I would recommend trying that out. I've just tested it with lens-shift and everything seems to work A-OK.

**Comment by generalsofttr** [comment]
Thank you very much.

**Comment by woistjadefox** [comment]
@generalsofttr we had a similar issue when we moved the near clipping plane of the standard camera in Unity. The problem was that the underwater curtain and underwater meniscus got clipped. So we created a separate script which moved these two objects on the local z axis towards the near clipping plane distance. Not sure if this goes in the same direction.

**Comment by generalsofttr** [comment]
@woistjadefox thank you very much for the info.

**Comment by generalsofttr** [comment]
@moosichu 
Using Unity 2019.2.6 , this branch (#299) caused other problems related to post processing. ( Input to postprocess is black. And we couldn't find a proper workaround for this problem )

If any quick solution or idea comes to your mind we will be happy to hear from you. Thank you very much for your support.

**Comment by generalsofttr** [comment]
@daleeidd Unfortunately upgrading Post Processsing Stack to 2.3.0 does not resolve those problems.  Thank you very much for your suggestion.

**Comment by daleeidd** [comment]
The new underwater effect is out in 4.12 which solves this issue. We have changed the implementation so it works with the PPv2 stack.

**Comment by daleeidd** [comment]
4.12 is out with the new underwater implementation which solves this problem.
