### ISSUE TITLE
Depth cache being triggered by Enviro reflection probe

### ISSUE THREAD

**Issue by mmaclaurin** [wave-harmonic/crest#478]
Every run, I get the following warning twice in the console:

RenderTexture.Create: Depth|ShadowMap RenderTexture requested without a depth buffer. Changing to a 16 bit depth buffer.
UnityEngine.Rendering.Universal.UniversalRenderPipeline:RenderSingleCamera(ScriptableRenderContext, Camera)
Crest.OceanDepthCache:BeginCameraRendering(ScriptableRenderContext, Camera) (at Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs:249)
UnityEngine.Camera:Render()
<RefreshInstant>d__37:MoveNext() (at Assets/Enviro - Sky and Weather/Core/Scripts/EnviroReflectionProbe.cs:402)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

It looks like the Enviro reflection probe is somehow invoking the Depth Cache renderer and forcing a new depth buffer to be allocated on the fly. 

URP
2019.3.f10
PC editor and PC target

I talked to Henrik (Enviro) about it and he didn't see anything he could do on his side. He does have a flag for enabling / disabling custom renders but when I disabled my depth cache went away entirely.

**Comment by huwb** [comment]
Thanks for this. Note to self for now..

It might be because we are hooking into OnBeginCameraRendering to initiate populating the depth cache. There might be another hook we can use, or if nothing else we might be able to guard against running for non main cameras like probe captures.

**Comment by Magic73** [comment]
This is the same issue of  #714 (fix inside)

**Comment by daleeidd** [comment]
We don't have Enviro to confirm that this is fixed, but 4.8 will change from using OnBeginCameraRendering to using Camera.Render which should solve this issue. Will wait for confirmation once 4.8 is released before closing.

**Comment by daleeidd** [comment]
@mmaclaurin @Magic73 4.8 is out. Please let me know if this solves the issue when you get a chance. Thanks!

**Comment by daleeidd** [comment]
Closing this one. I'll reopen if we get reports of the issue persisting.
