### ISSUE TITLE
Add instruction for adding object-water interaction to DWP boats

### ISSUE THREAD

**Issue by huwb** [wave-harmonic/crest#505]
We have good compatibility with DWP2, but the object water interaction doesnt work out of the box.

I think *ObjectWaterInteractionAdaptor* makes it possible to add interaction onto a boat without requiring code changes.

Help on this was requested on discord and i think we should add a section to the documentation.

**Comment by moosichu** [comment]
Do you think the Wiki or README should be the place for this? (it's where our existing third party documentation is hosted).

**Comment by huwb** [comment]
All the srp documentation is in the user guide so that would be the default choice, off the top of my head. Its a bit flexible as the birp userguide doesnt directly feed the srp userguide, but id generally vote for prioritising srp and keeping things simple.

**Comment by daleeidd** [comment]
I can add this in. Looking at https://github.com/wave-harmonic/crest/blob/a99bc369/master/crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteraction.cs#L63-L67 it should be added automatically?

**Comment by daleeidd** [comment]
OWI is deprecated so closing.
