### ISSUE TITLE
Dynamic Waves freak out on low simsteps

### ISSUE THREAD

**Issue by klauskobald** [wave-harmonic/crest#522]
This is between a Bug Report and a Feature request!
The problem is, that on flat water the objectinteraction creates tiny fluctuations which build up to cracy freaking out waves.
I found out, that this can be fixed by simply damping very tiny velocities like so:

in the UpdateDynWaves.compute shader change this line
`   vtp *= 1.0 - min(1.0, _Damping * dt);
`
into
`
if(vtp<0.0005) vtp*=0.8;`
`else vtp *= 1.0 - min(1.0, _Damping * dt);`

The constants 0.0005 and 0.8 could be discussed and maybe the should be exposed as shader parameters. The shown values work even for these extrem settings:
damping=0 
courant=3 
simsteps=1

(Sorry I have no time for finding out how pull request work)

**Comment by klauskobald** [comment]
ok - I think, we should forget my above suggestions! They create another problem: sustaining water bumps.

**Comment by huwb** [comment]
Yeah was wondering about that. What about applying that friction when both velocity is low, and wave height is small? Not sure, just a thought.

**Comment by klauskobald** [comment]
yes, that would help for sure. I did however not figure out, where the height value is stored.

**Comment by huwb** [comment]
It's `ftp` . f is the height and tp means `time positive` - one time step ahead.

**Comment by huwb** [comment]
I have a test/experimental PR which locks simulation rate, which should help with this. feedback welcome

https://github.com/crest-ocean/crest/pull/734

**Comment by huwb** [comment]
Will be fixed in 4.9

**Comment by daleeidd** [comment]
Thanks for reporting this. 4.9 has been released which solves this issue. The simulation may produce different results so tweaking may be required. Let us know if the issue persists.
