### ISSUE TITLE
White edges around objects [URP]

### ISSUE THREAD

**Issue by woistjadefox** [wave-harmonic/crest#529]
When the camera background color is set to solid and white I get these edges around objects which are in front of the ocean / water. Happens also with the underwater curtain. 
![ezgif-3-0678ba17aa2b](https://user-images.githubusercontent.com/9056181/83850570-6a6c8180-a711-11ea-80a3-fe80903648b0.gif)

Happens with Unity 2019.3.14f1 and the URP Crest v4.2 in the editor game view window and in standalone windows builds. Testing it on a GTX 2060s. 

In the discord channel we talked about this issue and @huwb mentioned that it might has something to do with the "averaged" depth buffer from Unity.

**Comment by woistjadefox** [comment]
What I forgot. It has also something to do with MSAA. It's not happening with MSAA turned of on the camera.

**Comment by huwb** [comment]
Thanks @woistjadefox .

I haven't quite understood the gif above. Those objects are in front of the water are they?

**Comment by OkoGoran** [comment]
Ah sorry, I couldn't show more of the picture. Yes, objects in front of the water on or below the surface.

**Comment by woistjadefox** [comment]
Ah sorry, I couldn't show more of the picture. Yes, objects in front of the water on or below the surface.

**Comment by daleeidd** [comment]
This is likely caused by a discrepancy between the depth texture and the opaque texture.

I couldn't reproduce this with MSAA using Crest 4.6 and Unity 2019.4. I could reproduce this if downsampling was applied to the camera opaque texture. Can you please re-test this and also try setting downsampling to none?

**Comment by daleeidd** [comment]
Fixed MSAA outline in 4.13.
