### ISSUE TITLE
Calculating waves on cpu for server based environments

### ISSUE THREAD

**Issue by TiToMoskito** [wave-harmonic/crest#530]
Is it possible to add the wave calculations on the cpu?
To enhance the perfomance, it could use the Unity's C# Job System.

Reason for this, is for projects who are made with multiplayer in mind and using an headless and non graphics dedicated server.

**Comment by huwb** [comment]
We have dabbled with this:

https://github.com/crest-ocean/crest/pull/157
https://github.com/crest-ocean/crest/pull/157

I think theres more to do to make us support server based environments. We currently require a GPU to be present for a number of reasons, but it would be possible to run a minimal version of the system I think.

I think that would mean doing height queries on the CPU and switching off a lot of the view-dependent stuff and all the lod data and everything.

I dont know when we'd be able to work on this but I'm happy to keep this issue open for discussion if it helps. if so i will rename this issue as having the waves calculate on the CPU is the minor part of this work, the major part of this work is to add a 'headless' mode to the system. Let me know if that makes sense @TiToMoskito

**Comment by huwb** [comment]
Misc thought - it just occurred to me - #268 copies a depth cache from the GPU to CPU in order to support deep vs shallow water. If there is no GPU at all, the cache would have to be populated another way, or would have to be loaded from a baked file (loading a texture may still require a GPU, so may have to be a custom file format.

**Comment by huwb** [comment]
Link: #811

**Comment by skaughtx0r** [comment]
I started playing around with the Flow sim to create water currents, but realized this will probably make the physics on my dedicated server even more out of sync with clients.

**Comment by daleeidd** [comment]
Linking #881

**Comment by daleeidd** [comment]
4.15 has been released with #881. I think with all of the advancements in this area we can close this. There is still room for improvement (like supporting wave attenuation) which is on the roadmap.
