### ISSUE TITLE
No normal maps heading 0 degrees and 180 degrees north

### ISSUE THREAD

**Issue by olavrv** [wave-harmonic/crest#534]
There are no normal maps on ocean surface at 0 and 180 degrees north, a strip without normalmaps throughout the ocean.

**Comment by daleeidd** [comment]
Thank you for reporting. Can you please provide more information like screenshot and pipeline?

**Comment by daleeidd** [comment]
Bump

**Comment by daleeidd** [comment]
I believe this was an issue that was solved a while ago. 4.9 will have the same fix for underwater if it is indeed the issue I am thinking of. Will close, but comment here if it wasn't solved.
