### ISSUE TITLE
Oculus Quest transparency and halo issue

### ISSUE THREAD

**Issue by starmind001** [wave-harmonic/crest#546]
**Describe the bug**
The water system has transparency issue with UI and only rendering in the left eye. Right eye goes black or has no transparency. This sometimes causes a halo/fresnel effect around gameobjects.
Waves, shoreline foam and wave foam are hit and miss. Sometimes they work and sometimes they don't. Everything works great in the editor.

**Screenshots / video**
https://youtu.be/EQdPXQRNq3Y

**Log**
There are no errors in the console.

**Versions**
Using 2019.3/URP

**To Reproduce**
To get the system to work on the quest, I had to turn off most of the shader and only use the top section.  Only normal mapping, underwater and caustics are enabled.

**Platform**
Oculus Quest

**Hardware**
What hardware are you seeing the issue on? GPU model is particularly useful.

**Additional context**
If you have a quest and want to test.
[https://drive.google.com/uc?export=download&id=1SEKgmTLetJR2SExw59FgB17kB-WyNQiY](url)

**Comment by daleeidd** [comment]
Taken from discord:
> Urp multipass(no single pass option available), no refraction, smoothness low, metallic low, forward rendering, linear lighting, depth and opaque selected. Pretty bare bones mostly the top section of  the shader.

**Comment by daleeidd** [comment]
Can you please confirm whether this is the builtin VR or the new XR package? You didn't seem certain on the discord.

**Comment by starmind001** [comment]
All I have done is add oculus integration and switch to android. The xr setting say they are going to be depreciated in the next update. Does that help?

**Comment by daleeidd** [comment]
It sounds like you are using the legacy VR system. Could you try the new XR system? It might work better for multi-pass.

**Comment by daleeidd** [comment]
#555 will now handle the right eye being black. Not sure if all of the other issues you have reported are related.

**Comment by daleeidd** [comment]
Thank you for reporting. I am going to close as we have since released the _Underwater Renderer_ which should be used instead. It also has expanded XR support. If you experience the same issues, please reopen.
