### ISSUE TITLE
VR URP Multipass with transparency ON objects in front of water have ghosting effect.

### ISSUE THREAD

**Issue by NiekoEugenijus** [wave-harmonic/crest#555]
**Describe the bug**
VR URP Multipass with transparency ON objects in front of water have ghosting effect. SinglePass works fine. Ghosting is affected by changing Renderque, but is still there. 

**Screenshots / video**
Only in VR device, not visible in monitor.

**Log**
No errors

**Versions**
URP 7.4.1, unity 2019.3 to 2019.4  all versions

**To Reproduce**
Enable multipassVR, we tried Vive Cosmos, Occulus Rift, WMR, HTC Vive

**Platform**
PC

**Hardware**
All PC's 

**Additional context**

**Comment by daleeidd** [comment]
Thank you for reporting. Is this only in one eye or both? Is the ghost trail black? Have you tried disabling transparency in the ocean material? Have you tried URP 7.3.1? Is this with the builtin legacy VR or the new XR package?

**Comment by NiekoEugenijus** [comment]
Thank you for reporting. Is this only in one eye or both? 
Only Right eye 

Is the ghost trail black? 
Yes
Have you tried disabling transparency in the ocean material?
yes, it helps
Have you tried URP 7.3.1? Is this with the builtin legacy VR or the new XR package?
We use legacy VR, we have tried 7.3.1 earlier, had similar issue.

**Comment by daleeidd** [comment]
Thanks.

I have investigated. I have submitted a bug to Unity. The opacity texture is black for one eye if the depth texture is also enabled.

I don't know if this will solve the entirety of the issue though. But it should be a good start. Will post here once I get a reply.

**Comment by daleeidd** [comment]
The issue has been processed. Remember to upvote if you want this fixed sooner than later:

https://issuetracker.unity3d.com/product/unity/issues/guid/1256604

**Comment by huwb** [comment]
Upvoted ⬆️

**Comment by daleeidd** [comment]
Unity fixed this in URP 7.7.0.
