### ISSUE TITLE
[URP] Shader compile error on URP 9.0.0 - LightingPhysicallyBased API

### ISSUE THREAD

**Issue by huwb** [wave-harmonic/crest#579]
As reported by Tom - LightingPhysicallyBased API function arguments have changed - theres a new bool argument added to the end - `specularHighlightsOff`.

Fix is to pass `false` as the last argument, but we need to figure out how to manage this across versions.

To investigate - are there shader defines that allow us to detect URP 9.0.0? Or can it be done through package version defines (will that work in shader land)?

**Comment by moosichu** [comment]
We can test when URP 9.0.0 comes out of preview - it still has some pretty serious bugs they might add an overload back-in that doesn't require the bool... if not I think yeah we will have to do some kind of check. I don't know if they define keywords in shader-land for this.

**Comment by huwb** [comment]
There is something already here

https://github.com/Unity-Technologies/Graphics/blob/master/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl#L730

I will try it out

**Comment by huwb** [comment]
Yeah trying on Unity 2020 uses URP 8.1, and its fine there.

I agree to wait, i'd be surprised if they dont overload it back in as it seems trivial to do so.

**Comment by daleeidd** [comment]
@moosichu There is this (seen it for 7.3 too): https://github.com/Unity-Technologies/Graphics/blob/master/com.unity.render-pipelines.core/ShaderLibrary/Version.hlsl

**Comment by daleeidd** [comment]
So HDRP 8.2 has replaced _IndirectLightingMultiplier with _IndirectDiffuseLightingMultiplier. And the latest HDRP 9.0 preview doesn't have these changes yet. I don't think it is even worth looking at preview packages anymore if they do this.

**Comment by huwb** [comment]
Agreed

**Comment by daleeidd** [comment]
Closing as I don't think anyone will be using URP 9.0.
