### ISSUE TITLE
Reflections Ray tracing HDRP

### ISSUE THREAD

**Issue by patrickgoud** [wave-harmonic/crest#627]
I’m trying to enable real time raytracing with the HDRP / dxr pipeline. 
At the moment it’s not supported. 
Anyone else interested so the developer could have some estimation if there are more people that would like this feature. 

Thanks,
Patrick

**Comment by JanuszBiela** [comment]
That would be great feature!

**Comment by streaman** [comment]
Would love it.

**Comment by celeronpm** [comment]
Yesssss! Please!!!

**Comment by huwb** [comment]
We made some progress, and are offering our sponsors (https://github.com/sponsors/wave-harmonic) an early test version of an ocean shader which should support all HDRP features.

**Comment by daleeidd** [comment]
This was introduced in 4.15. It requires Unity 2021.2 or later.
