### ISSUE TITLE
Waves and foams disappeared

### ISSUE THREAD

**Issue by willcatkins** [wave-harmonic/crest#635]
Hello, I'm using dynamic waves. It seems to be associated with the distance between the camera and the LOD of the ocean. When I get away from it, it will gradually disappear, but I hope it will always exist, even if its LOD is turned off.

But I didn't find a way to deal with this problem. Please tell me how to make the wave (foam) exist or change its LOD method. Thank you very much!

By the way,I have set the Ocean's MaxLOD to -1,because I need a very high altitude view.

**Comment by daleeidd** [comment]
Could you explain your use case? It sounds like the loss of detail at high altitudes is causing issues?

> but I hope it will always exist, even if its LOD is turned off.

It sounds like you want rendering high detail across the entire surface which would invalidate the purpose of the LOD system. Dynamic waves shouldn't really be relied on for gameplay since they are not deterministic. Animated waves will be more persistent.

**Comment by willcatkins** [comment]
Hi,sorry for late.

![Uploading 20200831204544.jpg…]()
![Uploading 20200831204549.jpg…]()
![20200831204552](https://user-images.githubusercontent.com/70247638/91734719-d9a52500-ebdd-11ea-8ec5-d6ff39139b0f.jpg)
![20200831204553](https://user-images.githubusercontent.com/70247638/91734726-dca01580-ebdd-11ea-84ea-fdf1dc86d9a1.jpg)
![20200831204559](https://user-images.githubusercontent.com/70247638/91734750-e6297d80-ebdd-11ea-8d2a-38ba5bc58cd9.jpg)

I don't  want rendering high detail,I just want to display the the wake of ships all the time.

**Comment by willcatkins** [comment]
![20200831204544](https://user-images.githubusercontent.com/70247638/91735830-72887000-ebdf-11ea-92d4-5ea0a1f63229.jpg)
![20200831204549](https://user-images.githubusercontent.com/70247638/91736086-c1360a00-ebdf-11ea-9378-ef44ea22ed54.jpg)

Upload the first two pictures again~~

**Comment by daleeidd** [comment]
Thanks. Can I please grab some more details like how high the camera is, a screenshot of the _Ocean Renderer_ component, and how strong the dynamic waves are for the boat wakes (_Strength_ on the material)?

**Comment by daleeidd** [comment]
4.13 will have a fix which should solve this problem.

**Comment by daleeidd** [comment]
4.13 is out. Please reopen if you still experience this issue.
