### ISSUE TITLE
Wave attenuation provider for "not" shallow water - behind walls, rocks, mountains.

### ISSUE THREAD

**Issue by klauskobald** [wave-harmonic/crest#656]
It would be great to be able to add geometry (squared planes would be sufficient) on a special layer, that does the same like the depth cache but without actually reducing the depth, because that would also influence the renderers water color.

Example use case:
there is no high waves behind a mountain or behind a seawall inside an harbour. Even smaller waves would be damped.

**Comment by daleeidd** [comment]
Just posting some possible workarounds for the time being:

1. Weigh in and out the gerstner waves to suit your needs. May not always be possible but could work if a lake is far enough from ocean
2. Make use of local gerstner waves keeping the global gerstner waves relatively flat
3. Use the shader "Crest/Inputs/Animated Waves/Set Water Height To Geometry" shader with _Register Anim Waves_ Input to flatten waves

**Comment by klauskobald** [comment]
I am now upgrading to the latest - looks great by the way and I am happy to see all the fixes we came up last year!
It seems I can use the new spline tech for this! 
Question: How do many splines affect performance? I am thinking of having some big splines on the windy side of the landmasses and some other on the leeward side and tiny splines for areas in harbours. This will be set up during runtime since I have now a very cool windmap feature that creates wind vectors around landmasses. So the main ocean object would have no waves on it at all. Do you see this as a good approach?

**Comment by daleeidd** [comment]
> It seems I can use the new spline tech for this, right?

Yes

> How do many splines affect performance? .. set up during runtime

Unfortunately, I don't have an answer for that other than I believe splines are more expensive than normal inputs.

> So the main ocean object would have no waves on it at all. Do you see this as a good approach?

Sounds like a good approach. We also have [feature/scale-waves](https://github.com/wave-harmonic/crest/compare/feature/scale-waves) which has been on my list to finish and merge in. It allows waves to be reduced using inputs.

**Comment by klauskobald** [comment]
hi,

> Am 18.07.2021 um 16:28 schrieb Dale Eidd ***@***.***>:
> 
> 
> It seems I can use the new spline tech for this, right?
> 
> Yes
> 
> How do many splines affect performance? .. set up during runtime
> 
> Unfortunately, I don't have an answer for that other than I believe splines are more expensive than normal inputs.
> 
> So the main ocean object would have no waves on it at all. Do you see this as a good approach?
> 
> Sounds like a good approach. We also have feature/scale-waves <https://github.com/wave-harmonic/crest/compare/feature/scale-waves> which has been on my list to finish and merge in. It allows waves to be reduced using inputs.
> 
> 

OH YES! It was me asking that before!
That would be great. Then I could keep one big ocean and locally dampen the waves!
But don´t forget to not only dampen but also take out the bigger waves leaving only the higher harmonics!
So a parameter for that would be great or better: a spectrum for that area that gets multiplied with the overall spectrum. 

Kind regards,
Klaus

**Comment by huwb** [comment]
The splines are similar/same cost to other inputs. 4 wave splines is similar cost to 4 wave components

But If you use wave splines with ShapeFFT and they share a spectrum then the waves are generated once and shared.

For wave attenuation that is wavelength dependent I recommend disabling shallow water colour (set it to the same as normal colour) and then use depth cache. Adding shallow water colour was a mistake, you can get the same or similar effect by tweaking depth fog density and colour of geometry below to get result. That's how other water solutions do it and it works well, and we'll likely move over to this some time soon for crest.

**Comment by klauskobald** [comment]
Oh yes ! I refactored everything to use the fog. Looks almost the same and disabling the shallow scattering will save some CPU as well, right? And for the depth - it´s actually soooo simple: I can deactivate the objects under water after the depth cache has been created. (stupid - I did not do that before!)  Not even multiple areas with splines are needed! Thank you guys - I am so happy with the update. It also runs way faster! 30fps on my old ipads. So, for me that issue is closed!

**Comment by huwb** [comment]
Ok cool :)

You can stick objects on a layer that isnt rendered (assuming you have a spare layer), if they're not moving around and not rendered they likely keep a pretty low profile (hopefully). But disabling works too.

Dale i'll let you decide whether to keep this open (for a simple wave scaling mechanism) or if the branch is enough to track it.

**Comment by daleeidd** [comment]
> disabling the shallow scattering will save some CPU as well, right?

It will save a little GPU.

> I refactored everything to use the fog. Looks almost the same, even better in distance

Sounds interesting. Are you able to share more about this?

**Comment by daleeidd** [comment]
Implemented in #888 and released with 4.13.
