### ISSUE TITLE
Additional camera with a render texture causes horizon line

### ISSUE THREAD

**Issue by KasperSeas** [wave-harmonic/crest#658]
**Describe the bug**
Once a second camera is added with render texture, the horizontal line bug appears. This has been done in the main scene in the examples. I don't think this is related to https://github.com/crest-ocean/crest/issues/456 since render texture wasn't mentioned.

**Screenshots / video**
This is what the horizon line artifact looks like.
![image (2)](https://user-images.githubusercontent.com/13711663/93940691-cd465080-fce1-11ea-8d90-6a132209254d.png)

These are components of the duplicated camera. Once the "ScreenProjectorRT" render texture is added, the line appears.
![image (2)](https://user-images.githubusercontent.com/13711663/93940594-9ff9a280-fce1-11ea-85a5-1e4fd9cf2ece.png)

**Log**
There are no warnings or errors

**Versions**
In Unity 2020.1.5f1, using HDRP 8.2.0, Crest Ocean System HDRP 4.5.0

**To Reproduce**
-You can reproduce this by duplicating the DemoCamera in the main scene in examples.
-Change duplicated camera output target display to Display 2 and Depth to 1
-Create and add render texture to duplicated camera's Target Texture.
-Remove Cam Controller and Lerp Cam scripts from duplicated camera
-Press play
-Go underwater add see the horizontal line

**Platform**
 - in Editor
 - Platform: win

**Hardware**
Processor: intel core i5-6600k
gpu: nvidia geforce gtx 1080

**Additional context**
none

**Comment by daleeidd** [comment]
Does it still happen if you remove the MainCamera tag from the duplicated camera?

**Comment by KasperSeas** [comment]
Hey deleeidd, yes it does still happen. It's not shown in the screenshot above but I just tried it rn

**Comment by daleeidd** [comment]
@KasperSeas sorry we haven't gotten around to this. Is it still an issue?

**Comment by psychoclast** [comment]
Yes, I'm having this issue too.  I use a secondary camera underwater for a sonar effect.

**Comment by daleeidd** [comment]
Pretty sure this is solved with 4.16. It adds support for multiple cameras.
