### ISSUE TITLE
Thin white lines flashing on surface

### ISSUE THREAD

**Issue by dmenefee** [wave-harmonic/crest#668]
Thin white lines in a grid pattern are visible on the ocean surface, flashing and sparkling. Different viewing angles make them more or less visible. Turning off transparency removes the lines, as does turning off the Enviro directional light.

<img width="884" alt="Screen Shot 2020-10-13 at 11 04 20 AM" src="https://user-images.githubusercontent.com/549633/95898451-e6bc4480-0d43-11eb-90dd-9addf7eb6313.png">

No log messages whatsoever.

**Versions**
Standard rendering pipeline. Unity 2019.4.12f1. Latest standard Crest from github.
I'm using Enviro with a standard setup. When I turn off the directional light, the lines disappear.

**To Reproduce**
Set camera to deferred.
I cannot reproduce this precise issue in the demos, but I can see odd artifacts in the three boats demo, and the scene view flashes a light blue color at random intervals.

**Platform**
 -editor
 - Mac

**Hardware**
MacBook Pro 2019 w/64GB RAM, 2TB disk, AMD Radeon Pro 5500M w/8GB.

**Additional context**
I've had this problem off and on for quite awhile.

**Comment by dmenefee** [comment]
Addendum: I did the recommended edits to the Ocean shader to accommodate Enviro.

**Comment by daleeidd** [comment]
Thank you for reporting. Are you using deferred rendering? Macs can be a little buggy with rendering from my experience so it might be a metal issue.

**Comment by dmenefee** [comment]
Yes, I’m using the deferred rendering path. Other assets require it... I am not surprised that there’s an issue that could relate to Metal. Any workarounds would be gratefully accepted.

Thanks
Dave

**Comment by daleeidd** [comment]
I could reproduce on Mac in the main scene (set camera to deferred), but not on Windows.

**Comment by daleeidd** [comment]
I found that reducing refraction to zero removes the artefacts.

Also, this [forum thread](https://forum.unity.com/threads/issue-on-mac-with-deferred-path-and-metal-in-graphics.768857/) might be related.

**Comment by dmenefee** [comment]
Thank you. That helped quite a bit, and the information is very useful!

cheers
Dave

**Comment by huwb** [comment]
@dmenefee could you please report a bug to unity using the reporter tool?

**Comment by daleeidd** [comment]
I checked this again in 2020.3.40 and it appears to be fixed.
