### ISSUE TITLE
How to display two different oceans with different materials in a scene

### ISSUE THREAD

**Issue by dogiracle** [wave-harmonic/crest#676]
How to display two different oceans with different materials in a scene

**Comment by daleeidd** [comment]
At this stage only a single ocean instance is available. This is being explored here #650. I'm not sure if it would cover this use case though/ For now you can blend materials using [Material.Lerp](https://docs.unity3d.com/ScriptReference/Material.Lerp.html).

**Comment by huwb** [comment]
An alternative which may work is to extend the water body script to allow override materials to be provided, so different water bodies could get different materials.  It probably won't be perfect but may get us some way there. I've been meaning to try it, will post if I do.

**Comment by huwb** [comment]
This is still on the list, it seems to always be one or two items further down than what we have bandwidth to look at, but it is slowly bubbling up..

We're hoping to increase our bandwidth through sponsorship and i wanted to mention that once here in case there is interest in supporting us: https://github.com/sponsors/wave-harmonic

**Comment by daleeidd** [comment]
This feature was added in 4.14 (#902).
