### ISSUE TITLE
Flickering ocean when game and scene view side-by-side

### ISSUE THREAD

**Issue by daleeidd** [wave-harmonic/crest#681]
**Describe the bug**
Flickering ocean when game and scene view side-by-side.

**Versions**
Crest 4.6

**To Reproduce**
Have game and scene view visible.

**Additional context**
This is a known limitation. Creating an issue so others can see it. #650 could help solve this and it is related to #540.

**Comment by daleeidd** [comment]
I am seeing flicking too with only the scene view open and using a scroll bar in the Editor on Mac (will check Window next time I am on there). Not a high priority but worth mentioning.

**Comment by huwb** [comment]
Yeah I wonder what this could be, or how to track it down :)

**Comment by daleeidd** [comment]
Appears to be fixed since 2020.3.40 so must've been a Unity bug.
