### ISSUE TITLE
UnderwaterEffect/Underwatercurtain stripes artifacts when going very deep underwater (-5000y)

### ISSUE THREAD

**Issue by BenjaminYde** [wave-harmonic/crest#703]
**Describe the bug**
When going very deep underwater (-5000y && ocean renderer.y == 0), the UnderWaterCurtainGeom/UnderwaterEffect creates very weird stripes when looking almost down.

**Screenshots / video**
![image](https://user-images.githubusercontent.com/44135938/100479503-bad80100-30ee-11eb-853f-b2a4eaf0c42f.png)

![image](https://user-images.githubusercontent.com/44135938/100479513-c3303c00-30ee-11eb-8577-c9b7647adb94.png)

**Log**
Nothing in the log.

**Versions**
Built in render pipeline - version 2020.14f1

**To Reproduce**
Just place the ocean renderer/camera pos at deep depths like 5000y or -5000y

**Platform**
Windows

**Hardware**
GPU: rtx 2060 super

**Comment by daleeidd** [comment]
Thanks. We might be able to mitigate or even solve this. But once you get to 5000 units, you should be looking into a solution to solve precision issues like floating origin. HDRP has camera relative rendering and URP will eventually get that too. We do have a floating origin component which you could try.

**Comment by BenjaminYde** [comment]
I used the floating origin component but I still have the same problem. Dunno if I'm doing something wrong with it?

I also added this line because it wasn't checking the treshold for the y-dir:
            if (Mathf.Abs(transform.position.y) > _threshold) newOrigin.y += transform.position.y;

![image](https://user-images.githubusercontent.com/44135938/100482089-9b44d680-30f6-11eb-83d3-2a7f3ef10866.png)

**Comment by daleeidd** [comment]
I had a look and indeed it doesn't solve the problem. Tried changing all halves to floats and no difference either.

However, increasing the near plane to 1.0 does appear to solve it. So it is likely a precision issue with some of the calculations in the curtain. But I have no solution.

This also affects URP. But it doesn't appear to affect the post-processing underwater branch. You can try it here #299

**Comment by daleeidd** [comment]
The new underwater effect will be available in 4.12 which solves this issue.

**Comment by daleeidd** [comment]
4.12 is out with the new underwater implementation which solves this problem.
