### ISSUE TITLE
Caustics showing up on inside of objects ie overhands, top and walls of underwater structures.  Probably should ignore downward facing normals etc.

### ISSUE THREAD

**Issue by holdingjason** [wave-harmonic/crest#710]
Here is a shot though of something interesting with caustics.  Not sure if there is anything to be done here and not a big deal but would look nice if we could avoid down facing normals for caustics perhaps.  See how we are getting them on all surfaces including the ceilings in this shot (I am not on latest btw)

> @Critter Cove We can use the depth and normals texture to accomplish this so it shouldn't be to difficult to add.

Dale 12/05/2020

![badcaustics](https://user-images.githubusercontent.com/42001313/102652158-7f938580-4122-11eb-9a1f-7d97327c501f.png)

**Comment by holdingjason** [comment]
Also here is a video showing off the issue as well.

https://twitter.com/i/status/1325873079461965828

**Comment by daleeidd** [comment]
Thanks. Another option that we should consider is sampling the shadow maps.

**Comment by holdingjason** [comment]
> Thanks. Another option that we should consider is sampling the shadow maps.

Yeah I could see that work as well.  Though it does not need to be perfect so I would go with the most performant option available unless its a big big trade off.  Thanks for taking a look.  Just looks bizarre right now inside of stuff underwater but not a show stopper by any means.

**Comment by huwb** [comment]
Was hoping this would be straightforward but we don't have a normal for the refracted scene.

We could reconstruct one by sampling the depth buffer multiple times don't this reliably across depth continuities etc is a topic in itself, and will cost perf.

Using the shadow maps seems like the best option. I'm guessing this would then be a URP/hdrp only fix.

**Comment by holdingjason** [comment]
Any way to just use a fixed world vector ie down up to a certain angle?

**Comment by Arugin** [comment]
Just fyi, you have acces to the normal buffer at least in HDRP.

**Comment by daleeidd** [comment]
URP 10 has a normal buffer.

Shadows will be a more comprehensive though.

**Comment by daleeidd** [comment]
#929 adds this for built-in. Will also be attempting other RPs for 4.14.

**Comment by daleeidd** [comment]
This feature has landed with 4.14.
