### ISSUE TITLE
Add compile symbol, to know from other packages, that Crest is installed

### ISSUE THREAD

**Issue by Magic73** [wave-harmonic/crest#715]
To improve integration with other packages, it would be useful for CREST to add its own build symbol so that integration with other packages can be managed.

Just add this:

```csharp
using System.Collections.Generic;
using System.Linq;
using UnityEditor;

public class CrestRemoveDefines : UnityEditor.AssetModificationProcessor
{
    static string symbols;

    public static void OnWillCreateAsset(string assetName)
    {
        AddDefineSymbol("CREST");
    }

    public static AssetDeleteResult OnWillDeleteAsset(string assetPath, RemoveAssetOptions rao)
    {
        RemoveDefineSymbol("CREST");

        return AssetDeleteResult.DidNotDelete;
    }

    public static void AddDefineSymbol(string symbol)
    {
        string definesString = PlayerSettings.GetScriptingDefineSymbolsForGroup(EditorUserBuildSettings.selectedBuildTargetGroup);
        List<string> allDefines = definesString.Split(';').ToList();
        allDefines.Add(symbol);
        PlayerSettings.SetScriptingDefineSymbolsForGroup(EditorUserBuildSettings.selectedBuildTargetGroup, string.Join(";", allDefines.ToArray()));
    }

    public static void RemoveDefineSymbol(string symbol)
    {
        string symbols = PlayerSettings.GetScriptingDefineSymbolsForGroup(EditorUserBuildSettings.selectedBuildTargetGroup);

        if (symbols.Contains(symbol))
        {
            symbols = symbols.Replace(symbol + "; ", "");
            symbols = symbols.Replace(symbol, "");
            PlayerSettings.SetScriptingDefineSymbolsForGroup(EditorUserBuildSettings.selectedBuildTargetGroup, symbols);
        }
    }
}
```

Then, from the other scripts, it can be used something like:
```
#if CREST
:
#endif
```

**Comment by daleeidd** [comment]
Thank you for the report.

I have a project which uses Crest URP and it has a *CREST_OCEAN_PRESENT* scripting symbol added by Unity. Did Unity not add this when importing from the asset store for you?

@huwb I don't know where this define is set as I couldn't find it in the source. Is this something that is set up in the asset store?

**Comment by Magic73** [comment]
No, I don't have it.
and there's no CREST_OCEAN_PRESENT inside the code.

I saw how Enviro, Aquas and Vegetation Studio did.
(Enviro integration files, use such defines to enable/disable integration scripts)

**Comment by huwb** [comment]
@daleeidd no it is not set up via the asset store. I also searched my mails/discord etc for CREST_OCEAN_PRESENT and it did not come up, so im not sure where that's coming from.

I'm generally in favour of adding this (thanks for the suggestion and pointers @Magic73 ). Dale let me know if you are happy to take this on, otherwise i can.

**Comment by Magic73** [comment]
👍 

In case, it would be useful adding also the version, ex: CREST_OCEAN_PRESENT_SRP or CREST_OCEAN_PRESENT_URP, CREST_OCEAN_PRESENT_HDRP

(so two def, one general and one with the version. again, I saw other assets doing this)

**Comment by huwb** [comment]
Yeah i was contemplating the same - agreed. Maybe CREST_OCEAN and CREST_OCEAN_xxRP, with the latter depending on the 'RP. but happy to include 'PRESENT' keyword in it as well if desired

**Comment by daleeidd** [comment]
@huwb sure I can do it.
