### ISSUE TITLE
Depth Cache scale issues

### ISSUE THREAD

**Issue by Magic73** [wave-harmonic/crest#716]
I'm not sure it's a bug, but I've tried to change all the parameters and can't get it to work as it should.
My scene is made up of many adjacent terrains. The total size is 5120x4096.

I created the OceanDepthCache object exactly like in the "main" example scene.
Inside, I added a new object with the RegisterSeaFloorDepthInput script attached.
I already have a question: **why do I have to rotate it 90 degrees on the X axis?**

I set the scale of the object exactly to those of the world, so: (5120,1,4096)
but by doing so, the result is a smaller depth map, and therefore the final result is wrong:

![image](https://user-images.githubusercontent.com/7645382/103455529-29ac0980-4cee-11eb-9420-9c2fab5e1aa4.png)

Notice the edges too, it's not a perfect rectangle but they are somewhat rounded. 

Anyway, to make it work I have to change the scale by setting a square area, so with scale (5120,1,5120).

![image](https://user-images.githubusercontent.com/7645382/103455564-81e30b80-4cee-11eb-8ce2-81574f870631.png)

but again, the edges are cut off.

Also I don't find a parameter, if there is one, so I can set the default maximum depth, that is the depth to use outside the terrains, otherwise the effect is generated whereby immediately after the terrains, the water changes suddenly of color.

**Versions**
URP

**Platform**
Any

**Comment by Magic73** [comment]
ok, after looking at the code for a while I understand why it wants a square area.
Use a single _resolution parameter to then build the final texture, instead of using two to manage rectangular areas as in my case.
perhaps, always wanting to use only one parameter, you could change it to a% scale value to apply to the X and Z values ​​of the object itself. In this way it would also be guaranteed the maintenance of the W / H ratio without having distortions.

In my case, for example, I could set this value to 0.125 (1/8), and therefore have a cache resolution equal to (640x520).

However, there is a sure bug, because changing the resolution, the cacheTexuture is never changed and always remains at 384x384.

This is because inside OceanDepthCache, in InitObjects the _cacheTexure object is no longer recreated.

            if (_cacheTexture == null)
            {
                _cacheTexture = MakeRT(false);
            }

while it should be changed to

            if (_cacheTexture == null || _cacheTexture.width != _resolution)
            {
                _cacheTexture = MakeRT(false);
            }

**Comment by daleeidd** [comment]
> why do I have to rotate it 90 degrees on the X axis?

The camera renders the depth into a texture from a top-down perspective.

> Also I don't find a parameter, if there is one, so I can set the default maximum depth, that is the depth to use outside the terrains, otherwise the effect is generated whereby immediately after the terrains, the water changes suddenly of color.

We don't have one. The default depth is 1000 metres. You could add an incline around the edges to handle both colour and wave attenuation. Or you could adjust the shallow sub-surface scattering colour depth properties on the ocean material. We might work out a better solution to this using a spline or interpolating depth.

> after looking at the code for a while I understand why it wants a square area.

All of our LOD data textures are square. Not sure yet if, for the depth cache, it is a hard limitation or we can accomodate rectangular sizes.

> the manual doesn't mention it.

Sorry about that. I will add something to the validation code which will inform users when they come across this.

> I don't understand why the edges are in that way.

It could be precision issues. Have you tried increasing the resolution? But it might be better to have multiple depth cache cameras instead. So maybe four depth cache cameras covering the terrain.

**Comment by Magic73** [comment]
Is it possible to have more than one depth cache camera? Oh, in this case, I will try to add a camera for each terrain, which are squared also :)

(I tried to increase the resolution, but doesn't change .. but don't forget the bug about _cacheTexure ... )

**Comment by Magic73** [comment]
No.. it doesn't work.
the scale of the object is not intended as the area to be examined, but is in fact the scale of the final result.

![image](https://user-images.githubusercontent.com/7645382/103492994-0b015c00-4e2f-11eb-9018-5f991f060da1.png)

I would have expected that with these settings, only the central part of the map would be taken into account for the depth calculation, instead the whole area is taken anyway, and the result scaled into a texture (2048x2048 in this case).

Honestly, I struggle to understand the logic.

As a result, adding additional depth cache cameras also results in replication of the same scan. :(

**Comment by daleeidd** [comment]
Did you click *Populate Cache*?

**Comment by Magic73** [comment]
Yes. I did.

**Comment by huwb** [comment]
Hello,

Yes only the area within the cache should be captured, so something is wrong. When we figure it out we can add validation to catch it in the future.

Are there scales on any parent transforms of the cache that might be confusing it? (Sanity check - do you have just one depth cache active for this test, so your not getting results from others?)

Are you able to reproduce the same issue in one of our example scenes like main.unity?

For future screenshots it would be useful to get quick mspaint-style annotations. its hard to understand from raw screenshots what the result is and what the expected result is.

I assume you've seen it but just to check, we have a video about setting up depth caches on the crest youtube: https://www.youtube.com/watch?v=jcmqUlboTUk

**Comment by daleeidd** [comment]
The above PR solves most of the issues here. We weren't updating the depth cache components as pointed out by @Magic73 which the PR solves. It also adds validation to inform users when the depth cache is outdated and if they are using a non uniform scale which is currently not support (due to rotations). Theses fixes will be out for Crest 4.9.

For the remaining issues:

> Also I don't find a parameter, if there is one, so I can set the default maximum depth, that is the depth to use outside the terrains, otherwise the effect is generated whereby immediately after the terrains, the water changes suddenly of color.

#726 was opened which will cover this problem.

> the edges are cut off.

I have opened #761 to address this issue.

**Comment by daleeidd** [comment]
4.9 is out which solves this issue (above post has more details). Thank you for the detailed report.
