### ISSUE TITLE
[HDRP] underwater mask precision

### ISSUE THREAD

**Issue by dkyeck** [wave-harmonic/crest#728]
hi there,

as we have encountered a lot of rendering issues caused by the underwater rendering leading to flat lines sometimes showing up above or below the water i looked into the UnderWaterPostProcessHDRP shader and – to be honest – peeked and poked around a bit.

it might be a sampling issue (uvs / half pixel offset?) but i did not looked into this.
what i did was adding a custom threshold when it comes to set "isBelowHorizon":
depending on if the the cam is above or below the ocean we tweak the threshold like this:
**float threshold = (WorldSpaceCameraPos.y > _OceanHeight) ? 0.001f : -0.001f;**
then we use this threshold to calculate "isBleowHorizon" like so:
**isBelowHorizon = dot(inout.uv - _HorizonPosNormal.xy, _HorizonPosNormal.zw) > threshold;**

as i mentioned: this is just some random peeking and poking around but i have the impression that adding the threshold eliminates most of the artifacts.
i would be happy to read your feedback on this :)

**Comment by huwb** [comment]
Thanks for this. We're planning to take another swing at fixing these issues soon and this is helpful.

Linking to #520

**Comment by daleeidd** [comment]
Thanks for providing this. I'll close this for now in favour of #520 to keep it together.
