### ISSUE TITLE
Underwater specks/dots

### ISSUE THREAD

**Issue by dkyeck** [wave-harmonic/crest#739]
underwater rendering shows up a lot of fireflies like shown below: small white pixel which do not receive the underwater effects.
![crestFireflies](https://user-images.githubusercontent.com/492095/106053640-5257d100-60eb-11eb-9d27-e212c97d855e.PNG)

i tracked it down in renderdoc and it looks as if the ocean mask contains little 1px gaps here and there which i assume are caused by the gpu rejecting very small triangles (little black dots in the eyes)
![oceanMaskFireFlies](https://user-images.githubusercontent.com/492095/106053918-a498f200-60eb-11eb-835c-38dfb48ee0f2.PNG)

so i started "filtering" the ocean mask in the "UnderwaterPostProcessHDRP" shader. initially i tried to use GATHER_RED_TEXTURE2D which did not work due to the fact that the texture is declared as TEXTURE2D_X. setting it to TEXTURE2D did not either so right now i just do 4 additional samples offsetting uvScreenSpace accordingly and accumulate the result in "maskSum". then i use:
mask = (maskSum > 2.0) ? 2.0 : mask; 
from my understanding this should set the mask to 2.0 if any of the 4 surrounding pixels has a vlaue larger than 2 or several have a value of 1...
but it does not fix the fireflies i see!
anything i am missing here or doing totally wrong?

**Comment by daleeidd** [comment]
Thanks. I think the next version of Crest (4.8) might solve this as it might be related to #665. Will check back with you once it is released.

Not sure why your solution doesn't work. I did something similar not long ago which cleared a small patch so it should work. But I think I was only checking along the horizon normal and not using a sum.

**Comment by dkyeck** [comment]
@daleeidd  no, it should not be related to them mentioned case...
but i forgot to change our custom blur pass as well which also samples the the ocean mask texture...
so adding:
mask = (maskSum >= 6.0) ? 2.0 : mask;
to this pass as well actualy kills most fireflies. i may test lowering the threshold here.
and i will have to test gather_red gain :)

**Comment by daleeidd** [comment]
You're right. I was able to see them when doing final testing for next release. There is *GATHER_RED_TEXTURE2D_X* defined in *com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/TextureXR.hlsl*.

**Comment by dkyeck** [comment]
GATHER_RED_TEXTURE2D_X dos not work with the declaration of the texture as TEXTURE2D_X.
and using the if vr is enabled did not help here either.
but that might be related to the fact that initially i forgot to tweak the blur shader as well.
actually using ddx/ddy should work too.

**Comment by dkyeck** [comment]
went with ddx/ddy which looks fine in our case:

float mddx = ddx(mask);
        float mddy = ddy(mask);
        if (mddx + mddy != 0.0 ) {
            mask = 2.0;
        }
