### ISSUE TITLE
Need a better shoreline wave and foam

### ISSUE THREAD

**Issue by LimLimLLM** [wave-harmonic/crest#743]
the foam on shoreline and far-sea use the same produce way isn't well enough
Suggest you can use depthcacheTex.r as UV to sample a 1D waveTex and work with sin and noise to make a better shoreline foam or wave?

**Comment by huwb** [comment]
Hello, thanks for starting this conversation. Could you please describe what is not good enough and what you want to achieve? 

As always there may be multiple solutions once we understand the problem.

**Comment by daleeidd** [comment]
Thank you for contributing. Closing this one for now due to being stale.
