### ISSUE TITLE
Warning when depth cache populates when using Azure[Sky]

### ISSUE THREAD

**Issue by huwb** [wave-harmonic/crest#750]
**Describe the bug**

This info is collected from the Azure Sky forum thread starting from this post: https://forum.unity.com/threads/azure-sky-dynamic-skybox.322773/page-27#post-6798431

Warning generated to log:

*You can only call cameraColorTarget inside the scope of a ScriptableRenderPass. Otherwise the pipeline camera target texture might have not been created or might have already been disposed*

With this callstack:

UnityEngine.Rendering.Universal.ScriptableRenderer:get_cameraColorTarget ()
AzureFogScatteringFeature:AddRenderPasses (UnityEngine.Rendering.Universal.ScriptableRenderer,UnityEngine.Rendering.Universal.RenderingData&) (at Assets/Plugins/Azure[Sky] Dynamic Skybox/Scripts/AzureFogScatteringFeature.cs:91)
UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal (UnityEngine.Rendering.RenderPipelineAsset,intptr,System.Collections.Generic.List`1<UnityEngine.Camera/RenderRequest>,Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle)
Crest.OceanDepthCache:populateCache () (at Assets/Plugins/Crest/Crest/Scripts/LodData/OceanDepthCache.cs:268)
Crest.OceanDepthCache:Start () (at Assets/Plugins/Crest/Crest/Scripts/LodData/OceanDepthCache.cs:100)

**Screenshots / video**

**Versions**
URP 10.x
Crest URP 4.8
*Which version of unity (including minor, i.e. 2019.1.0f2)?*

**To Reproduce**
Steps in thread linked above.

Sample project available if we want it.

**Platform**
 - Editor
 - *Platform (win/mac/...)*

**Hardware**

**Additional context**

**Comment by huwb** [comment]
@daleeidd you may have mentioned on discord that their render feature shoudl be skipping our depth cache camera. could you speak more to this mechanism? perhaps this is what is broken.

**Comment by daleeidd** [comment]
This is because we call camera.Render. SRFs are executed for every camera by default.

_AddRenderPasses_ is called per camera for every frame it is enabled, and this is where Azure developer can check cameras and avoid accessing that property for cameras that don't meet a certain criteria.

I've been filtering cameras for our SRFs by checking against _OceanRenderer.Instance.ViewCamera_ in the passes' _Execute_ method.

But I just realised we do have a solution on our end. We could create a forward renderer asset and assign it to the depth cache camera. This way it won't inherit all the extra passes and stuff that users configure. This actually might be the correct way to handle it.

**Comment by daleeidd** [comment]
I think this might not be our problem: https://forum.unity.com/threads/custom-renderer-features-broken-on-10-0-0-preview-26.980541/#post-6449553

Looks like Azure needs to update their code.

**Comment by huwb** [comment]
> AddRenderPasses is called per camera for every frame it is enabled, and this is where Azure developer can check cameras and avoid accessing that property for cameras that don't meet a certain criteria.

Which criteria - do you have something specific in mind or are you saying that some criteria needs to be found? If this question is made redundant by your follow up post then feel free to ignore me!

> Looks like Azure needs to update their code.

To

**Comment by huwb** [comment]
(oops sorry i meant "cancel comment" not "close with comment"!)

**Comment by huwb** [comment]
I'll ping this back to the Azure thread and close
