### ISSUE TITLE
Undo command reverts AssignLayer layer causing the ocean depth cache to be empty on next populate

### ISSUE THREAD

**Issue by daleeidd** [wave-harmonic/crest#752]
**Describe the bug**
The AssignLayer that we use in the examples assigns a layer on Awake. If there is an undo command, the layer change will revert. Then the cache becomes empty on next populate as nothing has the layer anymore. This will persist when entering play mode as Awake is not called again. It fixes itself when exiting play mode.

**Versions**
Ever since the editor feature.

**To Reproduce**
1. Open the main scene
2. Change a property
3. Edit > Undo
4. Click _Populate Cache_ button

**Additional context**
This is mainly limited to our examples since I don't expect many to use the assign layer.

**Possible solutions**
Changing persistent data in the editor is definitely something we should avoid.

One solution is to handle the editor case separately. The AssignLayer component can have a static dictionary which the ocean depth cache can access to use DrawRenderer or something rather than using layers when in the editor.

The other solution is to no longer use the AssignLayer component (extra benefit of removing lots of code). We set the layer as we would normally and use a LayerMask property on the depth cache. The following is what a user would see if no layer was assigned (still works as the layer int value is maintained):

<img width="598" alt="1" src="https://user-images.githubusercontent.com/5249806/107591563-c7cda200-6bbf-11eb-80ef-109ae566da4f.png">

For our examples, we could add a validation component which checks if the layer mask has a _Terrain_ layer and if it doesn't, then warn the user. Probably not necessary since it is limited to our example content anyway.

**Comment by daleeidd** [comment]
@huwb Let me know what you think on which approach or if we should leave it be for the time being.

**Comment by huwb** [comment]
Yeah happy to remove the AssignLayer. The evil thing is that we could assign it to layer N and that could be any random layer in the users project when they import, and was a bit of a mess. However that's less evil than this bug i guess

**Comment by daleeidd** [comment]
Fixed in 4.9
