### ISSUE TITLE
Animated waves input seems to have bad normals

### ISSUE THREAD

**Issue by gamemachine** [wave-harmonic/crest#754]
**Describe the bug**
This is with the input from texture but judging by the shader I think almost any noisy  displacement from inputs would probably cause this.  The source here was some FFT wave patterns.

**Screenshots / video**
![image](https://user-images.githubusercontent.com/75981/107863667-f55a5b80-6e0a-11eb-84f0-38e12ab713ae.png)

**Versions**
Crest 4.8 Unity 2020.2 HDRP 10.2

**Platform**
Editor/PC

**Hardware**
GTX 1080

**Comment by daleeidd** [comment]
Would you be able to provide the texture you're using so we can have a look? Can send it to one of us on Discord if you want to keep it private.

**Comment by huwb** [comment]
Also could you please annotate the screenshot to illustrate the issue.

The normals are computed from the displacements. It looks like the displacements are low res and the normals are low res correspondingly. Is detail the issue?

**Comment by daleeidd** [comment]
Thank you for reporting. Closing this one for now as it as gone stale. Please reopen if you continue to see the issue and can provide more information.
