### ISSUE TITLE
Crest Shader looks Pink in latest Unity / HDRP version - Did I miss something?

### ISSUE THREAD

**Issue by Framan87** [wave-harmonic/crest#755]
So, Quite simple actually, I have updated Unity to the latest version, and also updated the project without thinking about making a Backup (I know this is My fault), and now the Crest shader looks Pink. As if the New HDRP version does not support it.
It worked perfectly before the update, and I did NOT change anything in the project.  
So am I doing something wrong or do I just have to wait for an Update? Let me know if you need more info.

![Crest](https://user-images.githubusercontent.com/79063784/107891492-43f91a00-6f1f-11eb-8eb1-1c28c5623e4c.jpg)

**Versions**
HDRP version 10.2.2 - Unity version 2020.2.2f1

**Platform**
 - Pc , Windows only (for now)

**Comment by daleeidd** [comment]
Crest 4.8 should support latest HDRP.  There is a Unity bug preventing people from upgrading. Can you try upgrading, and if the problem persists, can you read the following from our Discord and see if that solves the problem?

> There is currently an issue with Unity's caching mechanism for the Asset Store. It will say you have Crest 4.7 downloaded but it will import whatever Crest version you currently have in the cache. Delete Crest from your Asset Store cache on your computer so you can download 4.7. The cache folder should be a sibling of the UPM/NPM cache folder which can be found using the following page from the manual https://docs.unity3d.com/Manual/upm-cache.html. The asset store folder will be called Asset Store or Asset Store-5.x. From there, Crest is located under Wave Harmonic/ScriptingEffects ... Unity says theres a fix for this in 2021.1.0b3 / 2020.2.3f1 / 2019.4.19f1 , which may be worth trying if upgrading is an option.

**Comment by Framan87** [comment]
So I tried to find the correct cache folder but appearently couldn't find it for unknown reason, Found the cache folder for almost every package but not that one. Anyway I just attempted to delete the package from the asset folder, redownloaded and reimported and it worked perfectly. Still I really appreciated your help. Thank you!
