### ISSUE TITLE
Distant Waves Jitter

### ISSUE THREAD

**Issue by andrew-sidereal** [wave-harmonic/crest#756]
**Describe the bug**
Distant shore water/foam jitters. This video shows it well:
https://youtu.be/7M2BOE4WPjs

Up-close it doesn't have this issue, only at a distance.

**Versions**
Built-in pipeline, 2019.4
Copy of Crest master branch from November.

**Comment by daleeidd** [comment]
Thanks for reporting. I remember you have a tide system where you move the ocean system up and down. Is this active for the video?

**Comment by andrew-sidereal** [comment]
Good memory. No that's not active in this scenario. It's at a constant height.

**Comment by andrew-sidereal** [comment]
I double-checked that everything around changing the depth cache height is totally removed. Issue still evident: https://youtu.be/AKZJr8I4wH0

**Comment by daleeidd** [comment]
I just realised this is a duplicated of #691. Let me know if it is not and I will re-open.
