### ISSUE TITLE
SphereWaterInteraction not working with DWP2

### ISSUE THREAD

**Issue by Catboiler** [wave-harmonic/crest#782]
**Describe the bug**
I've started a new scene, and imported the boat align normal prefab from the Crest demo, and also a ship from DWP2. I have copied over one of the objectwaterinteraction spheres to create a bow wave, but, while it works perfectly on the boat align normal, it doesn't work on the DWP ship.
In an added twist, if I start playing the scene, and immediately move the sphere to the boat align, then back to the DWP ship, it works as intended.
I'm just wondering if I've missed something - if the objectwaterinteraction needs something else on a parent object to work? Does it need the boat align normal / boat probes script or something?

**Versions**
Using Unity 2019.4.17f1, and the standard render pipeline.

**Platform**
Windows 10 Editor.

**Hardware**
CPU = i7 10700K, GPU RTX3080

**Comment by daleeidd** [comment]
[These lines might be of interest](https://github.com/wave-harmonic/crest/blob/master/crest/Assets/Crest/Crest/Scripts/Interaction/ObjectWaterInteraction.cs#L62-L66). Is it not adding the *ObjectWaterInteractionAdaptor*?

**Comment by huwb** [comment]
This is still on the list, it seems to always be one or two items further down than what we have bandwidth to look at, but it is slowly bubbling up..

We're hoping to increase our bandwidth through sponsorship and i wanted to mention that once here in case there is interest in supporting us: https://github.com/sponsors/wave-harmonic

**Comment by Catboiler** [comment]
As far as I'm aware, ObjectWaterInteractionAdaptor is being created. ObjectInteraction is working, it's the SphereWaterInteraction that just doesn't work if attached to a DWP2 object. Very odd.

**Comment by daleeidd** [comment]
@Catboiler are you still experience this with 4.14? SWI has been reworked so it might be more likely to work.

**Comment by daleeidd** [comment]
Closing as stale and likely no longer an issue.
