### ISSUE TITLE
Obsolete stuff in LodDataMgrShadow.cs

### ISSUE THREAD

**Issue by Estwalk** [wave-harmonic/crest#783]
**Describe the bug**
Obsotele ShadowCascadesOption

**Log**
Assets\Crest\Crest\Scripts\LodData\Shadows\LodDataMgrShadow.cs(96,26): warning CS0618: 'UniversalRenderPipelineAsset.shadowCascadeOption' is obsolete: 'This is obsolete, please use shadowCascadeCount instead.'
Assets\Crest\Crest\Scripts\LodData\Shadows\LodDataMgrShadow.cs(96,55): warning CS0618: 'ShadowCascadesOption' is obsolete: 'This is obsolete, please use shadowCascadeCount instead.'

**Versions**
Newest Unity 2020.2.7f1

**To Reproduce**
Import your asset in the newest unity version. If you miss obsolete asset warning open project again - it always shows up.

**Platform**
PC, windows 10. 
Universal Render Pipeline version

**Hardware**
Not important

**Comment by daleeidd** [comment]
Thanks. I will fix this once we upgrade to 2020 LTS.

**Comment by daleeidd** [comment]
Will be fixed in 4.12. Thank you for reporting.

**Comment by daleeidd** [comment]
4.12 is released with this fixed.
