### ISSUE TITLE
Can't access Variable due to no Namespace in "BoatAlignNormal"

### ISSUE THREAD

**Issue by CaptainUnknown** [wave-harmonic/crest#787]
**Problem:**
There is a problem with the script **"Boat Align Normal"**. The issue is that the script does not contain any namespaces, thus I'm unable to access any variables. What I want to access is bool variable **"controlledByPlayer"**.

**Log:**
`Assets\Boats\BoatProximity.cs(14,51): error CS1061: 'Component' does not contain a definition for 'controlledByPlayer' and no accessible extension method 'controlledByPlayer' accepting a first argument of type 'Component' could be found (are you missing a using directive or an assembly reference?)`

**Versions:**
Render Pipeline: _Built-in RP_
Version: _2020.1.9f1_

**Methods I tried:**
Any method I tried didn't work. These include:
- Creating the namespace myself then using "using static _<namespace>_;"
- Using "gameObject.getComponent("BoatAlignNormal").controlledByPlayer = false;"
- Using { get, set }

**My Script:**
```csharp
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using static BoatController; //removing "static" doesn't work. And I had to enclose the script into a namespace.


public class BoatProximity : MonoBehaviour
{
    bool onProximity = false;

    void Update()
    {
            if(Input.GetButtonDown("Action")){ this.gameObject.GetComponent("BoatController").controlledByPlayer = true; }
    }

    void OnTriggerEnter(Collider collider){ onProximity = true; }

    void OnTriggerExit(Collider collider){ onProximity = false; }

}
```

**Additional context:**
The root is that the script does not contain a namespace and I cannot access the variables within the script from my third party script (my own script).

**Comment by daleeidd** [comment]
The property is *_playerControlled* which is private (we are looking into making these public but you can do this yourself for now). *controlledByPlayer* doesn't exist. In your script you are trying to get a component called *BoatController* which I think you meant to use *BoatAlignNormal*.

I'll close this for now. I'll see any replies if you have more questions.

**Comment by CaptainUnknown** [comment]
Done, thanks!
What I was doing is that I created a namespace named *BoatController* and
tried to access it through that. But little did I know, I can also just
directly access script. I have also made the variable public.
So this line worked:
*this.getComponent<BoatAlignNormal>()_playerControlled = true; *

>
