### ISSUE TITLE
Shader Error on Unity 2020.3.2f1 LTS & HDRP 10.4.0

### ISSUE THREAD

**Issue by maslas** [wave-harmonic/crest#795]
## Description

After upgrade to Unity 2020.3.2f1 and HDRP 10.4.0 the system cannot compile the shader and sure enough the ocean turns purple. Crest was also updated to 4.9 with complete removal of the previous version 4.8 but the problem persists.

## Screenshot

![image](https://user-images.githubusercontent.com/71424994/113397991-93e45100-93a6-11eb-9541-f9cdfa267f09.png)

## Console Output

This the error in Unity editor.

`Shader error in 'Crest/Ocean': undeclared identifier '_DoubleSidedConstants' at /[...]/core/Library/PackageCache/com.unity.render-pipelines.high-definition@10.4.0/Runtime/Material/Decal/DecalUtilities.hlsl(273) (on d3d11)`

`Compiling Vertex program with INSTANCING_ON CREST_FOAM_ON CREST_CAUSTICS_ON
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR UNITY_PASS_SHADOWCASTER
Disabled keywords: LOD_FADE_CROSSFADE _PROJECTION_PERSPECTIVE _PROJECTION_ORTHOGRAPHIC CREST_FLOW_ON UNITY_NO_DXT5nm UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_COLORSPACE_GAMMA UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_RGBM_ENCODING UNITY_VIRTUAL_TEXTURING UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_ASTC_NORMALMAP_ENCODING SHADER_API_GLES30`

## Versions

Unity: 2020.3.2f1 LTS
HDRP: 10.4.0
Crest: 4.9

## To reproduce

* Start a new HDRP project.
* Install Crest.
* Open main scene from Crest-Examples.

## Platform

The problem is reproducible In Unity editor and is consistent on both a Windows and a Linux workstation.

## Hardware

Both systems have Intel CPUs and one works with an NVIDIA GTX-1070 GPU and the other with an NVIDIA GTX-1650 GPU.

**Comment by daleeidd** [comment]
Thanks. Will be fixed for the next release. There is a [workaround on Discord](https://discord.com/channels/559866092546424832/568134291540803595/824996146807177266).

**Comment by huwb** [comment]
In the meantime i'm putting the solution here, which is to add the lines in green:

![image](https://user-images.githubusercontent.com/939901/114618292-18857800-9ca1-11eb-8934-d3a9351b81ed.png)

**Comment by daleeidd** [comment]
4.10 is out which fixes this issue. Thanks for reporting.
