### ISSUE TITLE
MSAA causes outline on objects in front of ocean

### ISSUE THREAD

**Issue by metromeo** [wave-harmonic/crest#800]
**Describe the bug**
msaa not works correctly in hdrp

**Screenshots / video**
https://gfycat.com/damagedpinkladybug

**Versions**
HDRP v. 10.3 10.4
Crest 4.8 4.9, 
Unity 2020.2.7 2020.3.3

**To Reproduce**
Place any mesh with opaque material above water with another mesh with opaque material in background underwater

**Platform**
 - Editor and standalone
 - Win

**Hardware**
GForce GTX 1070, radeon 570

**Comment by daleeidd** [comment]
Thanks. Can I also grab a screenshot of the material for the object in the front?

**Comment by daleeidd** [comment]
Also, which shader are you using for the Terrain?

**Comment by metromeo** [comment]
Terrain material is simple hdrp/terrainlit
I reproduced this in main scene, just added black plane (which also on the first gif, under water with terrain) for difference with white terrain
also i uploaded part of the mesh, that have many edges - https://dropmefiles.com/5TMaZ

![1](https://user-images.githubusercontent.com/5053538/113973356-ddb8b580-9844-11eb-9ba4-ec2da32dae53.png)
![2](https://user-images.githubusercontent.com/5053538/113973363-e0b3a600-9844-11eb-9cd3-5c1e60d5b224.png)
![3](https://user-images.githubusercontent.com/5053538/113973364-e0b3a600-9844-11eb-9f55-d9c6b8d18446.png)
![4](https://user-images.githubusercontent.com/5053538/113973365-e0b3a600-9844-11eb-9c91-f322750aa206.png)

**Comment by daleeidd** [comment]
Thanks. I was able to reproduce. Not sure if I can solve this yet. If you look at the mesh up close you will see a fine outline when MSAA is enabled. And when you zoom out, like you have, it becomes more and more prominent. This is most likely caused by using something that has MSAA applied with something that doesn't have MSAA applied in our shader. It will need further investigation.

**Comment by daleeidd** [comment]
When we sample the depth buffer, choosing the maximum value around -and including- the sample point greatly reduces the issue. It still doesn't look great though and that is five samples (maybe more if using refraction).

I think having access to the MSAA depth might help with this. Although initial attempt was unsuccessful. Disappointing that this sort of thing is still an issue for developers to wrangle.

**Comment by huwb** [comment]
Thanks for the notes. Does it work in a standard SG? I'm assuming not but just checking. Seems like something unity should have a solution for.

Maybe others have complained about this online in the context of standard SGs.

**Comment by huwb** [comment]
A forum post. I think the reply is right that its always going to be a bit broken. He does propose something to address it although I didn't 100% follow, but maybe you could try it?

https://forum.unity.com/threads/anti-aliasing-and-shader-graph.1057298/

**Comment by huwb** [comment]
In another thread he seems to propose taking multiple samples as you did, from a quick glance at least

https://forum.unity.com/threads/fixing-screen-space-directional-shadows-and-anti-aliasing.379902/

**Comment by daleeidd** [comment]
> Thanks for the notes. Does it work in a standard SG? I'm assuming not but just checking. Seems like something unity should have a solution for.

I did try a standard shader and sampling the colour texture and the issue is not a prominent. I didn't test using depth too (which appears to be the the problem) as I moved on to isolating on the ocean shader.

> A forum post. I think the reply is right that its always going to be a bit broken. He does propose something to address it although I didn't 100% follow, but maybe you could try it?

Good find! Seems much simpler than the other one. Will give this a go.

> In another thread he seems to propose taking multiple samples as you did, from a quick glance at least

I am using that currently (it's the simpler example provided by a commenter). It mostly works but is probably more costly than it needs to be.

> And unity bouncing the issue, claiming it's fixed in URP/hdrp. I'm guessing it's fixed because it uses a different technique but linking here in case it's worth digging into

It might be. I'll have a look. They do have MSAA depth textures and sampling methods defined which might be what they are using. They just weren't bound for the transparent pass. Hopefully the simple fix works well enough.

Also, the [HDRP MSAA documentation](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.4/manual/Anti-Aliasing.html#multi-sample-anti-aliasing-msaa) lists some interesting caveats with using it.

**Comment by huwb** [comment]
Wow yeah according to that they force-disable a bunch of their techniques, and one that they leave enabled has the outline issue!

**Comment by metromeo** [comment]
Hellol, any news about fix?

**Comment by daleeidd** [comment]
@metromeo The issue is caused by two places in the SG. I had some success with one of the approaches at one place in the SG but struggled to replicate success elsewhere. I put this on hold for a little while. But I will evaluate it again sometime soon.

**Comment by qamelior** [comment]
Is there any potential workaround for this? 
We're getting really close to release with our game and having no MSAA creates lots of other visual problems for us.
Maybe there is some terrain shader fix or something crest-related which would at least reduce the impact of these artifacts?
We would be able to live with some level of picture degradation.

**Comment by qamelior** [comment]
> Is there any potential workaround for this?
> We're getting really close to release with our game and having no MSAA creates lots of other visual problems for us.
> Maybe there is some terrain shader fix or something crest-related which would at least reduce the impact of these artifacts?
> We would be able to live with some level of picture degradation.

@daleeidd can I get a follow up, please. We need to make a decision next week.

**Comment by daleeidd** [comment]
> Is there any potential workaround for this?
> We're getting really close to release with our game and having no MSAA creates lots of other visual problems for us.
> Maybe there is some terrain shader fix or something crest-related which would at least reduce the impact of these artifacts?
> We would be able to live with some level of picture degradation.

It's an issue with our shader. And there is no workaround I can think of from your end. I have a working solution but it is halfway complete as integrating it has some considerations. We will release a new version most likely this week or next at the latest and I will let you know if it makes it.

**Comment by qamelior** [comment]
@daleeidd just to be clear - we are currently using Unity 2019 version (some other assets we use require it). Will the fix be working on 2019 as well?

**Comment by daleeidd** [comment]
> @daleeidd just to be clear - we are currently using Unity 2019 version (some other assets we use require it). Will the fix be working on 2019 as well?

It won't. We cannot afford to support 2019 unfortunately.

**Comment by daleeidd** [comment]
A workaround was added in 4.13 which darkens the outline which in most cases is not noticeable. A proper solution is to sample the MSAA depth texture that Unity provides, but that proved to be difficult as it is hard to access. Maybe for the future.
