### ISSUE TITLE
Being inside underwater structure, looking outside

### ISSUE THREAD

**Issue by michaelheiml** [wave-harmonic/crest#802]
There might already be a solution for this, but I did not find it here or in the documentation:

Is there a way to achieve a situation where the user is inside an underwater structure (e.g. an underwater station with glass windows) and the ocean can be looked at from inside (no fog/light scattering/caustics inside the structure but only outside)?

Caustics inside structures are mentioned here as well:
https://github.com/wave-harmonic/crest/issues/710

**Comment by daleeidd** [comment]
Thanks. We have re-opened #376 which covers this issue. It was re-opened after your issue was opened, but will close this one in favour of continuing to track the issue there.
