### ISSUE TITLE
Support Input System Package

### ISSUE THREAD

**Issue by ghost** [wave-harmonic/crest#808]
The current demo scene example scripts (including the debug ui) do not support the new input system which results in multiple game-breaking errors as demonstrated in the attached file.

"You are trying to read input using the UnityEngine.Input class, but you have switched active input handling to Input System package in player settings."

A solution could be providing a toggle for each script (debug UI, camera control, boat controls, etc) that can be used to switch between hard-coded input versions of each.

default controls: Input.GeyKeyDown
input system controls: Keyboard.current.space.wasPressedThisFrame

https://docs.unity3d.com/Packages/com.unity.inputsystem@1.1/manual/index.html

https://user-images.githubusercontent.com/73148953/115870863-bf071100-a437-11eb-9064-ef499afb18c2.mp4

**Comment by daleeidd** [comment]
Thanks.

Unity provides define symbols for which input system is activated so we can support it without a toggle. For the case where both are, I think I was looking at just using the new one.

I was planning on doing this ages ago, but wanted to do it after #486 was merged (which never happened). Would you be willing to give your opinion on that proposal? I'll add support for this regardless. I'll prioritise it for 4.11.

**Comment by huwb** [comment]
This is still on the list, it seems to always be one or two items further down than what we have bandwidth to look at, but it is slowly bubbling up..

We're hoping to increase our bandwidth through sponsorship and i wanted to mention that once here in case there is interest in supporting us: https://github.com/sponsors/wave-harmonic

**Comment by sagron** [comment]
Submitted pull request #826

**Comment by daleeidd** [comment]
Basic support has been added to resolve exceptions. Will be out with 4.11. Thanks @sagron for the PR.

**Comment by daleeidd** [comment]
4.11 is out so I will close this.
