### ISSUE TITLE
Water does not render if Deploying via Unity Cloud Build (Windows x64)

### ISSUE THREAD

**Issue by danieldownes** [wave-harmonic/crest#812]
**Describe the bug**
Building master branch via Unity Cloud Build will produce a build with no water rendered.

**Screenshots / video**
![image](https://user-images.githubusercontent.com/1720388/116667376-03446500-a994-11eb-9629-b27f6220958e.png)

**Log**
Here is the full build log: https://pastebin.pl/view/6ac1bb8c

**Versions**
The master branch, as forked and unmodified per yesterday from this post.

**To Reproduce**
I forked the GitHub Repo. Set up Unity Cloud build with these build settings: (everything else default settings)
Platform: standalonewindows64
Repo branch: master
Sub-folder: crest
Unity version: Always Use Latest 2019.4

**Platform**
Windows x64 via Unity Cloud build

**Additional context**
I understand this may be a Unity Cloud Build issue, but I haven't had an problem like this previously and looking at the logs I think its a shader issue within Crest?

**Comment by danieldownes** [comment]
This may be due to Unity Cloud Build being hosted on a Linux install of Windows? That is my suspicion, but I can not confirmed.

**Comment by erikoegema** [comment]
I was running into the same issue. Cloud build uses MacOS as there builders. Is that a problem?

**Comment by daleeidd** [comment]
We had someone email us about Unity Cloud builds not working regardless of platform. They made a support request with Unity and said they would let us know the outcome. That was a few weeks ago.

> I can confirm that this is also a problem with Mac builds.

@erikoegema What specific problem are you seeing on Mac?

**Comment by huwb** [comment]
I think Mac should use Metal and Linux should use Vulkan. Can the backend be configured for unity cloud build?

**Comment by daleeidd** [comment]
@danieldownes @erikoegema We heard back from a user that spoke with UCB team. Disabling the following code in apparently works:
_Crest/Crest/Scripts/OceanRenderer.cs (OnEnable)_
```csharp
if (!VerifyRequirements())
{
enabled = false;
return;
}
```

**Comment by huwb** [comment]
We've opened the linked PR (#860), the change is fairly simple (and is what Dale mentions above). If anyone is able to help us confirm this fix please let us know. Thanks!

**Comment by huwb** [comment]
Merged and will go out soon in 4.12
