### ISSUE TITLE
Periodic (looping) gerstner wave?

### ISSUE THREAD

**Issue by kpietraszko** [wave-harmonic/crest#848]
Is it possible to set up the wave spectrum in a way that would make the wave loop seamlessly? Ideally with a period < 1 min. I saw that generating the wavelenghts uses some randomized offsets to break patterns in the wave, which could be an issue.
I'm asking because I'd like to cache a grid of sampled water heights on disk, in order to get much more performant height sampling for my buoyancy system. That's gonna be on a server so can't use compute shaders.

**Comment by huwb** [comment]
Oh sorry i never replied here. Anyway we're chatting directly and will make FFT loop. Just replying so Dale's aware.

**Comment by huwb** [comment]
Closing as the gerstner system is deprecated
