### ISSUE TITLE
Tearing on lake with spline waves above sea level

### ISSUE THREAD

**Issue by daleeidd** [wave-harmonic/crest#864]
**Describe the bug**
User eckhart3d reported tearing on the ocean surface. Their setup is a lake which is ~40m above sea level (~251m). It only occurs when a ShapeGerstner is used with a spline so the waves themselves cause tearing.

**Screenshots / video**
![1](https://cdn.discordapp.com/attachments/577081395718127646/859067032267128842/crest3.jpg)
![2](https://cdn.discordapp.com/attachments/577081395718127646/859154046903255069/crest4.jpg)

**Versions**
- Unity 2021.1.4f1
- HDRP 11
- Crest 4.11

**To Reproduce**
TODO: Need to reproduce it myself first.

**Additional context**
Setting the lake to sea level solved the problem for them. I think also setting the sea level to zero also solves the problem. But investigating the issue may be worth it. Not sure if this HDRP specific.

**Comment by huwb** [comment]
The final local water body change will store the sea level in a channel, because the precision of half floats dies quickly with large values. A y displacement of 40 might be sucking out all the precision. I'm not certain that this is the issue, but hacking the texture type to be floats may be a hacky fix, or test at least.

**Comment by daleeidd** [comment]
Turns out it was precision and increasing precision from 16 to 32 solved it. Going to add the texture format as an option. For anyone wanting this now, change R16G16B16A16_SFloat to R32G32B32A32_SFloat in the following:

_Assets/Crest/Crest/Scripts/LodData/LodDataMgrAnimWaves.cs_

**Comment by daleeidd** [comment]
4.13 will have an option to change the texture format for increased precision to solve this problem.

**Comment by daleeidd** [comment]
4.13 is out which solves this issue.
