### ISSUE TITLE
SampleShadowsURP.Enable() gets called after LodDataMgrShadow.Start() which outputs an Error

### ISSUE THREAD

**Issue by klauskobald** [wave-harmonic/crest#874]
**Describe the bug**
Not really a bug, because shadows work after that message "To support shadowing, a Custom renderer....." - seems to be only a notification.

**Versions**
Which render pipeline (built-in/LWRP/HDRP)? Which version of LWRP/HDRP? Which version of unity (including minor, i.e. 2019.1.0f2)? 

2020.3.14

**Description**
I have a special setup which activates and deactivates the ocean system during the game when user selects different settings.
So I am not sure, if that is only the case for me.
But anyhow the order of scripts called is often a problem. So you should maybe use IENumerators that wait for a state or use events, so that components get activated in the right order.

**Comment by daleeidd** [comment]
I forgot to remove that error as it is no longer applicable. It will be fixed in 4.13.

> So you should maybe use IENumerators that wait for a state or use events, so that components get activated in the right order.

Can you share more on this approach? We have #629 to support delayed initialisation of the ocean. But would love something nicer.

**Comment by daleeidd** [comment]
4.13 is out which removes this error message.
