### ISSUE TITLE
Shader debug symbols are always on

### ISSUE THREAD

**Issue by joravainen** [wave-harmonic/crest#936]
**Describe the bug**
Ocean.shader has the following code in it:

#if _COMPILESHADERWITHDEBUGINFO_ON
#pragma enable_d3d11_debug_symbols
#endif

This code falsely assumes that the debug symbols would be disabled when the given toggle is off. However, Unity does not atm allow preprocessor conditionals to affect pragmas this way. This means that the debug symbols are always enabled here and the shader is compiled with optimizations disabled. To actually disable the debug symbols, one must comment out the line or remove it.

**Platform**
This affects Windows Editor and builds made on Windows Editor. 
Mac ignores this pragma due to technical limitations with the FXC compiler on the platform.

**Additional context**
Bumped into this while investigating this https://issuetracker.unity3d.com/issues/windows-shader-system-shader-compiler-throws-ipc-exception-on-windows-version-of-editor
Greetings from Unity Shader Management team ;)

**Comment by daleeidd** [comment]
Thank you for letting us know :^)
