### ISSUE TITLE
ShapeFFT - make _respectShallowWaterAttenuation public?

### ISSUE THREAD

**Issue by Chris1234567899** [wave-harmonic/crest#953]
Any reason, why `_respectShallowWaterAttenuation` is private unlike the other parameters?

I'd like to manipulate that value at runtime. I have a weather system in place where I control wind strength and wave multipliers and so forth, but for higher waves I need to increase the attenuation, so low parts of the terrain don't get flooded. But at lower wind strengths, the attenuation can be less, so it gives me a nice shore line.

**Comment by daleeidd** [comment]
Sure. Done for 4.15.

**Comment by Chris1234567899** [comment]
Cool, thanks!

**Comment by daleeidd** [comment]
Closing as 4.15 is out.
