### ISSUE TITLE
Unity Volumetric Clouds modules not rendering in front of the ocean when they're in local space viewed from above the clouds

### ISSUE THREAD

**Issue by jomath229** [wave-harmonic/crest#963]
**Describe the bug**
The clouds render before the ocean, and are not written to the depth buffer since they're volumetric, so the ocean overrides their output.

First solution i thinked about is to render clouds after the ocean or render the ocean before the clouds, but then the clouds would render underwater if the camera was above water. 
Second solution i could think of is to actually create a mesh for the ocean that writes to the depth buffer that the volumetric cloud will use to fix the issue of solution 1.

**Screenshots / video**
Viewed from ground level, everything looks fine:

![image](https://user-images.githubusercontent.com/49660042/147052030-bca4226c-261d-4615-bdee-0e17f3de7224.png)

But when we get really high up in the air, the ocean plane overrides their render:

![image](https://user-images.githubusercontent.com/49660042/147052141-68600fe1-a0bf-4c6f-8dbb-a99fed823f7a.png)

**Versions**
2021.2.4f1 HDRP
**To Reproduce**
Enable the volumetric clouds in the HDRP global settings and then add the Volumetric Clouds to the scene volume in any example scenes and set "Local Clouds" to true, so you can "fly" trough them.

**Platform**
 - Editor and probably standalone
 - Windows 10

**Hardware**
GPU: RTX 3070

**Additional context**
Having no info about the cloud render when drawing the ocean simply acts like they're not there when drawing the ocean, thus overriding their render.

**Comment by daleeidd** [comment]
This is an issue for any transparent shader including Unity's as the cloud pass is before the transparent pass. Clouds are pretty new still so it is likely Unity has created a solution for handling transparent objects yet. A workaround is to set the ocean to Opaque when at a certain height. You'll need change the material UI by going to the **bottom** of the following file and swapping the editors around:
_Assets/Crest/Crest/Shaders/Ocean.shader_
From
```shader
    CustomEditor "Crest.OceanShaderGUI"
    // CustomEditor "Rendering.HighDefinition.LitShaderGraphGUI"
```
To
```shader
    // CustomEditor "Crest.OceanShaderGUI"
    CustomEditor "Rendering.HighDefinition.LitShaderGraphGUI"
```

**Comment by jomath229** [comment]
After testing some different transparent materials in the frame debugger, right now the default transparent material for hdrp fades the cloud down, but they're still visible. Maybe there's some sort of buffer unity uses to let the cloud render over transparent objects. Couldn't pin point what it was tho. If you wanna test it out, just make a super big cube with the lit transparent mat and you'll still see the cloud. But thank you! at that height it won't be noticable that the ocean became opaque so this fixes my issue :).

**Comment by daleeidd** [comment]
> right now the default transparent material for hdrp fades the cloud down, but they're still visible

If the transparent material is fading the cloud then it is rendering over the cloud. The cloud shouldn't be affected by the transparent objects behind it.

If you lower the fog density on the ocean shader enough you will also see the clouds too (faded by the ocean fog).

**Comment by jomath229** [comment]
Ah makes sense! Thanks for the input and happy holidays!

**Comment by daleeidd** [comment]
This is now possible with Unity 6 and 4.20.1. Set the Refraction Model to something other than None.
