### ISSUE TITLE
Dynamic waves are present in the editor and are absent in the build due to inaccuracy in the code

### ISSUE THREAD

**Issue by aaakkkaaa** [wave-harmonic/crest#971]
**Describe the bug**
Dynamic waves work well, when running an app in Unity editor mode, but completely absent in standalone build. 
The problem is that the script "SphereWaterInteraction.cs" ("\Project\Assets\Crest\Crest\Scripts\Interaction\SphereWaterInteraction.cs") uses the method Shader.Find("Crest/Inputs/Dynamic Waves/Sphere-Water Interaction").

**Screenshots / video**

![Shader_Find](https://user-images.githubusercontent.com/42075485/148102526-7f822cbe-2822-4461-be33-405cb568caf9.jpg)

This code works seamlessly in editor mode. But, since there are no references to this shader in the project scene, Unity does not include the shader in the player build. As a result, the Shader.Find method returns null, which causes an error and aborting the script.

This is one reason to use "Find" in Unity with care.
There are several ways to solve this problem, they are described in the Unity documentation: https://docs.unity3d.com/2021.2/Documentation/ScriptReference/Shader.Find.html

Fix it please. Some users may do it themselves in their projects, but others may have difficulty to find the cause and will not be able to fully enjoy the wonderful Crest Ocean product.

**Versions**
Unity 2021.2.7f1
Render pipeline URP 12.1.2
Crest Ocean System 4.14 for URP

**To Reproduce**
Make a Windows build with Crest example scene "boat.unity".

**Platform**
Standalone Windows

**Hardware**
Not important.

**Comment by daleeidd** [comment]
Thank you for reporting. We will have this fixed for the next release.

**Comment by huwb** [comment]
Thanks again. Fixed merge and will be out in 4.15.

**Comment by daleeidd** [comment]
For anyone who needs this now, move the following:
_Crest/Crest/Shaders/OceanInputs/DynWavesSphereWaterInteraction.shader_
To the following:
_Crest/Crest/Shaders/Resources_

**Comment by daleeidd** [comment]
> For anyone who needs this now, move the following:
> _Crest/Crest/Shaders/OceanInputs/DynWavesSphereWaterInteraction.shader_
> To the following:
> _Crest/Crest/Shaders/Resources_

With 4.15 we attempted to fix but didn't do it properly... if having issues with dynamic waves, then move the following (could be in either of these locations):
> _Crest/Crest/Shaders/OceanInputs/DynWavesSphereWaterInteraction.shader_
> _Crest/Crest/Shaders/Resources/DynWavesSphereWaterInteraction.shader_
To the following:
> _Crest/Crest/Shaders/OceanInputs/Resources_

**Comment by daleeidd** [comment]
We made a mistake with fixing this so some users upgrading had issues. 4.15.2 should solve that problem and help current users navigate the problem better.

**Comment by daleeidd** [comment]
4.15.2 is out with the fix.
