### ISSUE TITLE
Texture, Meshes and Material Memory never cleaned due to hideFlags and no Release call when switching scenes

### ISSUE THREAD

**Issue by lorenaweder** [wave-harmonic/crest#999]
Hi! Running an app with several scenes with different instances of an Ocean in them, loading one, another, then back to an menu/into screen (separate Unity scenes all of them) I observed that the profiler shows an increased amount of RenderTextures, Textures, Meshes and Materials each time I return to this intro scene. There's an unload unused resources being called in the middle, but due to the hideFlags of several things some stuff is never cleaned.

Some places where this is found:
- https://github.com/wave-harmonic/crest/blob/master/crest/Assets/Crest/Crest/Scripts/OceanBuilder.cs#L346
- https://github.com/wave-harmonic/crest/blob/master/crest/Assets/Crest/Crest/Scripts/LodData/RegisterClipSurfaceInput.cs#L145
- In the version I'm using also Crest/Scripts/Helpers/CustomPassHelpers.cs
- No code seems to call Release() for the FFTCompute unless new waves are created, but because of the scene switching this also doesn't clean things and I see with each run an accumulation of _tempFFT1, _tempFFT2, etc textures showing up in the profiler. From this script https://github.com/wave-harmonic/crest/blob/master/crest/Assets/Crest/Crest/Scripts/Shapes/FFT/FFTCompute.cs#L76

Maybe I'm using something wrong, but looking at the code itself it looks like a proper memory leak. The ones I found more and more on each run are:

Materials, from ShapeFFT.cs:
_matGenerateWavesGlobal
_matGenerateWavesGeometry

Textures from FFTCompute.cs:
_texButterfly
_texSpectrumControls

RenderTextures from FFTCompute.cs:
_spectrumInit
_spectrumHeight
_spectrumDisplaceX
_spectrumDisplaceZ
_tempFFT1
_tempFFT2
_tempFFT3

Meshes from OceanBuilder.cs:
Each Mesh created from BuildOceanPatch()

--
Unity Version: 2021.2.3f1
Ocean: 4.14 for HDRP (but some of the code remains the same in master in new versions)

**Comment by lorenaweder** [comment]
After more digging into this, I found out that the Textures and RenderTextures leaking in relation to the FFTCompute were caused by the CrestShapeFFT Spectrum property not having a SO assigned in one scene. To reproduce you can create 2 scenes with Oceans Renderers and CrestShapeFFT components, not assign the Shape in one, switch between scenes and an Empty one and observe in the profiler how the Texture count on the memory tab increases.

**Comment by daleeidd** [comment]
Thanks for the detailed report. I'll look into fixing this.

**Comment by daleeidd** [comment]
I've added two PRs above which address leaks. I believe it addresses all of them.

**Comment by lorenaweder** [comment]
Thank you for quickly addressing this, I'll check it out!

**Comment by lorenaweder** [comment]
No, the issue is also present in the editor.

Empty scene:
![image](https://user-images.githubusercontent.com/13229280/162904570-b55e96ab-63d6-4c2e-ad6b-a24ac7d17e0c.png)

Button goes into this scene:
![image](https://user-images.githubusercontent.com/13229280/162904348-05e29038-b88d-427d-9d5b-2c19973ee08a.png)

Button back to the empty scene:
![image](https://user-images.githubusercontent.com/13229280/162904765-dd191f84-9879-400c-9802-da3c8ccbe93f.png)

Repeating the process a second time:
![image](https://user-images.githubusercontent.com/13229280/162904937-b543c319-ad54-4d36-bab0-3178dc5734e2.png)

**Comment by daleeidd** [comment]
Thanks! #1007 has that last one fixed.

**Comment by daleeidd** [comment]
4.15.2 is out so I close this. If we missed one, you will still be able to reply here. Thank you for your help.
